{
  "hash": "ff026f238f689de005530c0e2c70dba5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Associação entre duas variáveis qualitativas\"\ndescription: \"Análise da associação entre variáveis qualitativas, uso de tabelas de contingência e estatísticas de associação.\"\ncategories: [\n          \"Estatística\",\n          \"Análise qualitativa\",\n          \"Tabelas de contingência\",\n          \"Medidas de associação\"\n        ]\n\nimage: \"images/biquali.jpg\"\nexecute:\n  echo: true\n  warning: false\n  include: true\n  message: false\n---\n\n\n\n\n:::{.callout-tip collapse=\"true\"}\n## Pacotes e funções utilizadas no capítulo\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gt)\nlibrary(patchwork)\nlibrary(gridExtra)\nsource('scripts/assoc-municipies.r')\n```\n:::\n\n\n\n\n:::\n\nImagine que haverá uma obra de revitalização de uma área na região central da cidade. A obra implicará na melhoria de acesso, de segurança e na oferta de serviços. Entretanto como levará tempo para ser concluída, haverá ações de remoção de moradias irregulares, interdição de ruas e avenidas por longos períodos, etc. A prefeitura encomenda uma pesquisa para saber a opinião dos munícipes. A cada entrevistado são feitas duas perguntas:\n\n1. Qual sua opinião sobre a necessidade de realização da obra?\n\n- [ ] A favor\n- [ ] Contra\n\n2. Você reside na região diretamente afetada:\n\n- [ ] Residente\n- [ ] Não-Residente\n\nA base de dados completa está disponível em [datasets](https://github.com/FCopf/datasets){target=\"_blank\"}\n\n\nCom estas entrevistas desejamos responder à seguinte questão:\n\n:::{.callout-note}\n## Questão do capítulo\n\nMoradores `Residentes` da região central têm uma opinião **consistentemente** diferente de moradores `Não-residentes` no que se refere a ser `A favor` ou `Contra` a obra?\n\n:::\n\nImporte a base de dados\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmun = read_delim('https://raw.githubusercontent.com/FCopf/datasets/refs/heads/main/Entrevista_municipes.csv',\n                  delim = ',')\n\nn_amostra = 12\nn = nrow(mun)  # Número de entrevistados\n```\n:::\n\n\n\n\nApós entrevistar 200 pessoas selecionadas ao acaso de uma lista da moradores da cidade, foi construída uma tabela com três colunas: `Entrevistado` (sequência numérica do primeiro ao último respondente), `Opinião` e `Moradia`. \n\n\nVeja os primeiros 12 resultados das entrevistas:\n\n\n\n\n\n::: {#tbl-municipies .cell tbl-cap='Respostas dos primeiros munícipies entrevistados.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"pxsljfflhl\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#pxsljfflhl table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#pxsljfflhl thead, #pxsljfflhl tbody, #pxsljfflhl tfoot, #pxsljfflhl tr, #pxsljfflhl td, #pxsljfflhl th {\n  border-style: none;\n}\n\n#pxsljfflhl p {\n  margin: 0;\n  padding: 0;\n}\n\n#pxsljfflhl .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#pxsljfflhl .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#pxsljfflhl .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#pxsljfflhl .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#pxsljfflhl .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pxsljfflhl .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pxsljfflhl .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#pxsljfflhl .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#pxsljfflhl .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#pxsljfflhl .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#pxsljfflhl .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#pxsljfflhl .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#pxsljfflhl .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#pxsljfflhl .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#pxsljfflhl .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#pxsljfflhl .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#pxsljfflhl .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#pxsljfflhl .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#pxsljfflhl .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxsljfflhl .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#pxsljfflhl .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#pxsljfflhl .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#pxsljfflhl .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxsljfflhl .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#pxsljfflhl .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#pxsljfflhl .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pxsljfflhl .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxsljfflhl .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#pxsljfflhl .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pxsljfflhl .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#pxsljfflhl .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#pxsljfflhl .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pxsljfflhl .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxsljfflhl .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#pxsljfflhl .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#pxsljfflhl .gt_left {\n  text-align: left;\n}\n\n#pxsljfflhl .gt_center {\n  text-align: center;\n}\n\n#pxsljfflhl .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#pxsljfflhl .gt_font_normal {\n  font-weight: normal;\n}\n\n#pxsljfflhl .gt_font_bold {\n  font-weight: bold;\n}\n\n#pxsljfflhl .gt_font_italic {\n  font-style: italic;\n}\n\n#pxsljfflhl .gt_super {\n  font-size: 65%;\n}\n\n#pxsljfflhl .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#pxsljfflhl .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#pxsljfflhl .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#pxsljfflhl .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#pxsljfflhl .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#pxsljfflhl .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#pxsljfflhl .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#pxsljfflhl .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#pxsljfflhl div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Entrevistado\">Entrevistado</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Opiniao\">Opiniao</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Moradia\">Moradia</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Entrevistado\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Opiniao\" class=\"gt_row gt_left\">A favor</td>\n<td headers=\"Moradia\" class=\"gt_row gt_left\">Residente</td></tr>\n    <tr><td headers=\"Entrevistado\" class=\"gt_row gt_right\">2</td>\n<td headers=\"Opiniao\" class=\"gt_row gt_left\">A favor</td>\n<td headers=\"Moradia\" class=\"gt_row gt_left\">Residente</td></tr>\n    <tr><td headers=\"Entrevistado\" class=\"gt_row gt_right\">3</td>\n<td headers=\"Opiniao\" class=\"gt_row gt_left\">A favor</td>\n<td headers=\"Moradia\" class=\"gt_row gt_left\">Residente</td></tr>\n    <tr><td headers=\"Entrevistado\" class=\"gt_row gt_right\">4</td>\n<td headers=\"Opiniao\" class=\"gt_row gt_left\">A favor</td>\n<td headers=\"Moradia\" class=\"gt_row gt_left\">Residente</td></tr>\n    <tr><td headers=\"Entrevistado\" class=\"gt_row gt_right\">5</td>\n<td headers=\"Opiniao\" class=\"gt_row gt_left\">Contra</td>\n<td headers=\"Moradia\" class=\"gt_row gt_left\">Não-Residente</td></tr>\n    <tr><td headers=\"Entrevistado\" class=\"gt_row gt_right\">6</td>\n<td headers=\"Opiniao\" class=\"gt_row gt_left\">Contra</td>\n<td headers=\"Moradia\" class=\"gt_row gt_left\">Residente</td></tr>\n    <tr><td headers=\"Entrevistado\" class=\"gt_row gt_right\">7</td>\n<td headers=\"Opiniao\" class=\"gt_row gt_left\">A favor</td>\n<td headers=\"Moradia\" class=\"gt_row gt_left\">Não-Residente</td></tr>\n    <tr><td headers=\"Entrevistado\" class=\"gt_row gt_right\">8</td>\n<td headers=\"Opiniao\" class=\"gt_row gt_left\">Contra</td>\n<td headers=\"Moradia\" class=\"gt_row gt_left\">Não-Residente</td></tr>\n    <tr><td headers=\"Entrevistado\" class=\"gt_row gt_right\">9</td>\n<td headers=\"Opiniao\" class=\"gt_row gt_left\">A favor</td>\n<td headers=\"Moradia\" class=\"gt_row gt_left\">Não-Residente</td></tr>\n    <tr><td headers=\"Entrevistado\" class=\"gt_row gt_right\">10</td>\n<td headers=\"Opiniao\" class=\"gt_row gt_left\">A favor</td>\n<td headers=\"Moradia\" class=\"gt_row gt_left\">Não-Residente</td></tr>\n    <tr><td headers=\"Entrevistado\" class=\"gt_row gt_right\">11</td>\n<td headers=\"Opiniao\" class=\"gt_row gt_left\">A favor</td>\n<td headers=\"Moradia\" class=\"gt_row gt_left\">Residente</td></tr>\n    <tr><td headers=\"Entrevistado\" class=\"gt_row gt_right\">12</td>\n<td headers=\"Opiniao\" class=\"gt_row gt_left\">A favor</td>\n<td headers=\"Moradia\" class=\"gt_row gt_left\">Não-Residente</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nEstão descritos na @tbl-municipies os resultados das primeiras 12 entrevistas, onde é possível ver ao menos uma combinação de todas as possíveis respostas. O entrevistado pode ser: \n\n+ `A favor` e ser `Residente` da região; \n\n+ `A favor` e ser `Não-Residente`; \n\n+ `Contra` e ser `Residente`; \n\n+ `Contra` e ser `Não-Residente`. \n\n## Tabelas de frequência e gráficos de barras\n\nInicialmente, vamos representar cada uma das variáveis por meio de uma tabela de frequência dos 200 entrevistados.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nresumo_opiniao = mun |> \n  group_by(Opiniao) |> \n  summarise(Op_n = n()) |> \n  mutate(Op_rel = Op_n/sum(Op_n))\n\nresumo_opiniao |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"orhcvbwega\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#orhcvbwega table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#orhcvbwega thead, #orhcvbwega tbody, #orhcvbwega tfoot, #orhcvbwega tr, #orhcvbwega td, #orhcvbwega th {\n  border-style: none;\n}\n\n#orhcvbwega p {\n  margin: 0;\n  padding: 0;\n}\n\n#orhcvbwega .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#orhcvbwega .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#orhcvbwega .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#orhcvbwega .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#orhcvbwega .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#orhcvbwega .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#orhcvbwega .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#orhcvbwega .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#orhcvbwega .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#orhcvbwega .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#orhcvbwega .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#orhcvbwega .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#orhcvbwega .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#orhcvbwega .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#orhcvbwega .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#orhcvbwega .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#orhcvbwega .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#orhcvbwega .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#orhcvbwega .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#orhcvbwega .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#orhcvbwega .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#orhcvbwega .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#orhcvbwega .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#orhcvbwega .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#orhcvbwega .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#orhcvbwega .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#orhcvbwega .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#orhcvbwega .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#orhcvbwega .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#orhcvbwega .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#orhcvbwega .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#orhcvbwega .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#orhcvbwega .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#orhcvbwega .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#orhcvbwega .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#orhcvbwega .gt_left {\n  text-align: left;\n}\n\n#orhcvbwega .gt_center {\n  text-align: center;\n}\n\n#orhcvbwega .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#orhcvbwega .gt_font_normal {\n  font-weight: normal;\n}\n\n#orhcvbwega .gt_font_bold {\n  font-weight: bold;\n}\n\n#orhcvbwega .gt_font_italic {\n  font-style: italic;\n}\n\n#orhcvbwega .gt_super {\n  font-size: 65%;\n}\n\n#orhcvbwega .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#orhcvbwega .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#orhcvbwega .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#orhcvbwega .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#orhcvbwega .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#orhcvbwega .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#orhcvbwega .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#orhcvbwega .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#orhcvbwega div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Opiniao\">Opiniao</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Op_n\">Op_n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Op_rel\">Op_rel</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Opiniao\" class=\"gt_row gt_left\">A favor</td>\n<td headers=\"Op_n\" class=\"gt_row gt_right\">144</td>\n<td headers=\"Op_rel\" class=\"gt_row gt_right\">0.72</td></tr>\n    <tr><td headers=\"Opiniao\" class=\"gt_row gt_left\">Contra</td>\n<td headers=\"Op_n\" class=\"gt_row gt_right\">56</td>\n<td headers=\"Op_rel\" class=\"gt_row gt_right\">0.28</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nDas $200$ respostas tivemos $144$ pessoas `A favor` ($72\\%$) e $56$ pessoas `Contra` ($28\\%$).\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nresumo_opiniao = mun |> \n  group_by(Opiniao) |> \n  summarise(Op_n = n()) |> \n  mutate(Op_rel = Op_n/sum(Op_n))\n\nresumo_opiniao |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jaxvyvxrso\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jaxvyvxrso table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jaxvyvxrso thead, #jaxvyvxrso tbody, #jaxvyvxrso tfoot, #jaxvyvxrso tr, #jaxvyvxrso td, #jaxvyvxrso th {\n  border-style: none;\n}\n\n#jaxvyvxrso p {\n  margin: 0;\n  padding: 0;\n}\n\n#jaxvyvxrso .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jaxvyvxrso .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jaxvyvxrso .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jaxvyvxrso .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jaxvyvxrso .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jaxvyvxrso .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jaxvyvxrso .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jaxvyvxrso .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jaxvyvxrso .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jaxvyvxrso .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jaxvyvxrso .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jaxvyvxrso .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jaxvyvxrso .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jaxvyvxrso .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jaxvyvxrso .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jaxvyvxrso .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jaxvyvxrso .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jaxvyvxrso .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jaxvyvxrso .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jaxvyvxrso .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jaxvyvxrso .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jaxvyvxrso .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jaxvyvxrso .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jaxvyvxrso .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jaxvyvxrso .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jaxvyvxrso .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jaxvyvxrso .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jaxvyvxrso .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jaxvyvxrso .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jaxvyvxrso .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jaxvyvxrso .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jaxvyvxrso .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jaxvyvxrso .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jaxvyvxrso .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jaxvyvxrso .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jaxvyvxrso .gt_left {\n  text-align: left;\n}\n\n#jaxvyvxrso .gt_center {\n  text-align: center;\n}\n\n#jaxvyvxrso .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jaxvyvxrso .gt_font_normal {\n  font-weight: normal;\n}\n\n#jaxvyvxrso .gt_font_bold {\n  font-weight: bold;\n}\n\n#jaxvyvxrso .gt_font_italic {\n  font-style: italic;\n}\n\n#jaxvyvxrso .gt_super {\n  font-size: 65%;\n}\n\n#jaxvyvxrso .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jaxvyvxrso .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jaxvyvxrso .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jaxvyvxrso .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jaxvyvxrso .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jaxvyvxrso .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jaxvyvxrso .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jaxvyvxrso .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jaxvyvxrso div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Opiniao\">Opiniao</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Op_n\">Op_n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Op_rel\">Op_rel</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Opiniao\" class=\"gt_row gt_left\">A favor</td>\n<td headers=\"Op_n\" class=\"gt_row gt_right\">144</td>\n<td headers=\"Op_rel\" class=\"gt_row gt_right\">0.72</td></tr>\n    <tr><td headers=\"Opiniao\" class=\"gt_row gt_left\">Contra</td>\n<td headers=\"Op_n\" class=\"gt_row gt_right\">56</td>\n<td headers=\"Op_rel\" class=\"gt_row gt_right\">0.28</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\nCom relação ao local de residência:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nresumo_morad = mun |> \n  group_by(Moradia) |> \n  summarise(Morad_n = n()) |> \n  mutate(Morad_rel = Morad_n/sum(Morad_n))\n\nresumo_morad |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"wwldhqhfig\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wwldhqhfig table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wwldhqhfig thead, #wwldhqhfig tbody, #wwldhqhfig tfoot, #wwldhqhfig tr, #wwldhqhfig td, #wwldhqhfig th {\n  border-style: none;\n}\n\n#wwldhqhfig p {\n  margin: 0;\n  padding: 0;\n}\n\n#wwldhqhfig .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wwldhqhfig .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wwldhqhfig .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wwldhqhfig .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wwldhqhfig .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wwldhqhfig .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wwldhqhfig .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wwldhqhfig .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wwldhqhfig .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wwldhqhfig .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wwldhqhfig .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wwldhqhfig .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wwldhqhfig .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wwldhqhfig .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wwldhqhfig .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wwldhqhfig .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wwldhqhfig .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wwldhqhfig .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wwldhqhfig .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wwldhqhfig .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wwldhqhfig .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wwldhqhfig .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wwldhqhfig .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wwldhqhfig .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wwldhqhfig .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wwldhqhfig .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wwldhqhfig .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wwldhqhfig .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wwldhqhfig .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wwldhqhfig .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wwldhqhfig .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wwldhqhfig .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wwldhqhfig .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wwldhqhfig .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wwldhqhfig .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wwldhqhfig .gt_left {\n  text-align: left;\n}\n\n#wwldhqhfig .gt_center {\n  text-align: center;\n}\n\n#wwldhqhfig .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wwldhqhfig .gt_font_normal {\n  font-weight: normal;\n}\n\n#wwldhqhfig .gt_font_bold {\n  font-weight: bold;\n}\n\n#wwldhqhfig .gt_font_italic {\n  font-style: italic;\n}\n\n#wwldhqhfig .gt_super {\n  font-size: 65%;\n}\n\n#wwldhqhfig .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wwldhqhfig .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wwldhqhfig .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wwldhqhfig .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wwldhqhfig .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wwldhqhfig .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wwldhqhfig .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#wwldhqhfig .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#wwldhqhfig div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Moradia\">Moradia</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Morad_n\">Morad_n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Morad_rel\">Morad_rel</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Moradia\" class=\"gt_row gt_left\">Não-Residente</td>\n<td headers=\"Morad_n\" class=\"gt_row gt_right\">117</td>\n<td headers=\"Morad_rel\" class=\"gt_row gt_right\">0.585</td></tr>\n    <tr><td headers=\"Moradia\" class=\"gt_row gt_left\">Residente</td>\n<td headers=\"Morad_n\" class=\"gt_row gt_right\">83</td>\n<td headers=\"Morad_rel\" class=\"gt_row gt_right\">0.415</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nResponderam à entrevistas um total de $117$ pessoas `Não-Residente` ($58.5\\%$) e $83$ pessoas `Residente` ($41.5\\%$)\n\nSe visualizarmos estes totais em gráficos de barras individuais teremos:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nplt_op = ggplot(mun, aes(x = Opiniao)) +\n  geom_bar(fill = 'darkblue', color = 'white') +\n  coord_cartesian(ylim = c(0, 150)) +\n  labs(y = 'Número de respostas') +\n  theme_classic(base_size = 15)\n\nplt_morad = ggplot(mun, aes(x = Moradia)) +\n  geom_bar(fill = 'darkred', color = 'white') +\n  coord_cartesian(ylim = c(0, 150)) +\n  labs(y = 'Número de respostas') +\n  theme_classic(base_size = 15)\n\nplt_op + plt_morad\n```\n\n::: {.cell-output-display}\n![Respostas dos munícipies entrevistados para cada questão separadamente.](biquali_files/figure-html/fig-municipies-indiv-1.png){#fig-municipies-indiv width=672}\n:::\n:::\n\n\n\n\nExiste portanto um predomínio de pessoas `A Favor` e um ligeiro predomínio de entrevistados `Não-Residentes`.\n\nPara responder à questão do capítulo, precisamos verificar se existe alguma **associação** entre as respostas dadas às duas perguntas explorando a *distribuição conjunta* dos totais respondidos.\n\n## Tabelas de contingência\n\nTabelas de contigência são organizadas para verificarmos a associação entre duas variáveis qualitativas. São conhecidas também como tabelas de *dupla entrada*. Nas colunas estão os níveis da variável $X$ e nas linhas os níveis da variável $Y$.\n\nPara nosso exemplo, podemos fazer simplesmente:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntcont = table(mun$Opiniao, mun$Moradia)\ntcont\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         \n          Não-Residente Residente\n  A favor            81        63\n  Contra             36        20\n```\n\n\n:::\n:::\n\n\n\n\nTemos:\n\n+ 81 - A favor e Não-Residente;\n\n+ 63 - A favor e Residente;\n\n+ 36 - Contra e Não-Residente;\n\n+ 20 - Contra e Residente\n\nPodemos ver os totais marginais das linhas:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntcont_linhas = apply(tcont, 1, sum)\ntcont_linhas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA favor  Contra \n    144      56 \n```\n\n\n:::\n:::\n\n\n\n\nOu os totais marginais das colunas:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntcont_colunas = apply(tcont, 2, sum)\ntcont_colunas\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNão-Residente     Residente \n          117            83 \n```\n\n\n:::\n:::\n\n\n\n\nQue são justamente os totais que verificamos nas distribuições individuais.\n\nSe quisermos ver as frequências relativas *marginais* podemos fazer:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrel_linha = prop.table(tcont, 1)\ntrel_linha\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         \n          Não-Residente Residente\n  A favor     0.5625000 0.4375000\n  Contra      0.6428571 0.3571429\n```\n\n\n:::\n:::\n\n\n\n\nNeste caso estamos vendo as **frequências relativas das linhas**, isto é, cada linha nesta tabela soma $1$. O que vemos nesta tabela é que: \n\n+ dos $144$ entrevistados que são A favor, cerca de $56.25\\%$ são Não-Residente, enquanto os demais $43.75\\%$ são Residente\n\n+ dos $56$ entrevistados que são Contra, cerca de $64.29\\%$ são Não-Residente, enquanto os demais $35.71\\%$ são Residente\n\nPodemos fazer exatamente o mesmo olhando para as **frequências marginais por colunas**:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrel_coluna = prop.table(tcont, 2)\ntrel_coluna\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         \n          Não-Residente Residente\n  A favor     0.6923077 0.7590361\n  Contra      0.3076923 0.2409639\n```\n\n\n:::\n:::\n\n\n\n\nNeste caso são as **colunas** que somam $1$, portanto:\n\n+ dos $117$ entrevistados que são Não-Residente, cerca de $69.23\\%$ são A favor, enquanto os demais $30.77\\%$ são Contra\n\n+ dos $83$ entrevistados que são Residente, cerca de $75.9\\%$ são A favor, enquanto os demais $75.9\\%$ são Contra\n\nPodemos finalmente ver a frequência relativa conjunta:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrel_conjunta = prop.table(tcont)\ntrel_conjunta\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         \n          Não-Residente Residente\n  A favor         0.405     0.315\n  Contra          0.180     0.100\n```\n\n\n:::\n:::\n\n\n\n\nEm que o somatório das linhas é igual a:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntcont_linhas / sum(tcont_linhas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nA favor  Contra \n   0.72    0.28 \n```\n\n\n:::\n:::\n\n\n\n\nindicando os valores relativos das opiniões `A Favor` e `Contra`.\n\nO somatório das colunas é igual a:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntcont_colunas / sum(tcont_colunas)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNão-Residente     Residente \n        0.585         0.415 \n```\n\n\n:::\n:::\n\n\n\n\nindicando os valores relativos de `Não-Residentes` e `Residentes`.\n\nNa tabela de frequência relativa conjunta, o somatório total da tabela deve ser igual a $1$.\n\n## O gráfico de barras para duas variáveis qualitativas\n\nExistem várias formas de gerar um gráfico de barras combinando as duas variáveis. Se quisermos utilizar a própria tabela de contingência obtida a partir do comando `table(mun$Opiniao, mun$Moradia)`, podemos utilizar o comando `barplot()`. Por outro lado, se quisermos utilizar a tabela original de dados (objeto `mun`) podemos fazer uso do pacote ggplot2:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nplt_bar1 = ggplot(mun) +\n  aes(x = Moradia, fill = Opiniao) +\n  geom_bar(color = 'white', position = 'dodge') +\n  scale_fill_manual(values = c('Contra' = 'darkred',\n                               'A favor' = 'darkblue')) +\n  coord_cartesian(ylim = c(0, 80)) +\n  labs(y = 'Número de respostas') +\n  theme_classic(base_size = 15)\n\nplt_bar1\n```\n\n::: {.cell-output-display}\n![Respostas dos munícipies entrevistados combinando local de moradia e opinião.](biquali_files/figure-html/fig-municipies-1.png){#fig-municipies width=672}\n:::\n:::\n\n\n\n\nVeja que nesta figura, existem mais opiniões `A favor`, **independente** do entrevistado ser ou não residente da região central. Este padrão é o mesmo que observamos no gráfico da variável `Opinião` isoladamente, o que sugere **não haver** associação entre as variáveis `Opinião` e `Moradia`. Ao que parece, a opinião de um entrevistado sobre a construção da obra **não depende** de seu local de moradia.\n\n:::{.callout-note}\n## Exemplos de associações entre duas variáveis\n\nAbaixo são apresentadas quatro situações em que **existe** associação `Opinião` e `Moradia`.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](biquali_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\n:::\n\nEm todos estes exemplos, note que a relação as opiniões `A favor` ou `Contra` *dependem* se o entrevistado é ou não `Residente` na região. Esses padrões configuram diferentes tipos de associação entre as variáveis `Opinião` e `Moradia`, a saber:\n\n+ Figura A: `Não-Residentes` tendem a ser `A favor` e `Residentes` são em sua maioria `Contra`;\n\n+ Figura B: todos tendem a ser `Contra`, mas a diferença de opiniões é maior entre os `Residentes`;\n\n+ Figura C: `Não-Residentes` tendem a ser `Contra`, enquanto não parece haver diferenças entre os `Residentes`;\n\n+ Figura D: `Residentes` tendem a ser `A favor`, enquanto não parece haver diferenças entre os `Residentes`;\n\n\n## Medindo a discrepância com o índice de $\\chi^2$ de Pearson\n\nO índice de qui-quadrado ($\\chi^2$) mede a discrepância entre os valores **observados** e os valores **esperados** em uma tabela de contingência.\n\nDigamos que um município tenha $20\\%$ de sua população morando em área Rural e os outros $80\\%$ em área Urbana. Se fizermos uma amostragem *ao acaso* dos moradores é esperado que esta frequência relativa se reflita na amostra. Neste caso se sorteamos $200$ pessoas, seria esperado:\n\n+ Zona Rural: $40$ moradores\n\n+ Zona Urbana $160$ moradores\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nEntretando, se fazemos um sorteio ao acaso, haverá alguma variação ao redor destes valores, de modo que as frequências observadas ($o$) deverão ser diferentes das esperadas ($e$). O $\\chi^2$ mede a discrepância entre $o$ e $e$ para cada célula de uma tabela de contigência como:\n\n$$\\chi^2 = \\sum_{i=1}^{n}\\frac{(o_i - e_i)^2}{e_i}$$\nPara uma tabela de frequências, devemos determinar portanto os valores de $o_i$ e $e_i$.\n\nSuponha que uma amostra de $200$ moradores tenha resultado em:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(10)\nnor = sum(rbinom(n = n, size = 1, prob = pr))\nMoradia_obs = data.frame(Regiao = c(rep('Rural', nor),\n                           rep('Urbana', n - nor)))\n\ntb_dfo = table(Moradia_obs)\ntb_dfo\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRegiao\n Rural Urbana \n    31    169 \n```\n\n\n:::\n:::\n\n\n\n\nAs frequências observadas e esperadas serão:\n\n+ Zona Rural: \n\n$o_{Rural} = 31$\n\n$e_{Rural} = 0.2 \\times 200 = 40$\n\n+ Zona Urbana\n\n$o_{Urbana} = 169$\n\n$e_{Urbana} = 0.8 \\times 200 = 160$\n\nDe modo que o valor de $\\chi^2$ será:\n\n$\\chi^2 = \\frac{(31 - 40)^2}{40} + \\frac{(169 - 160)^2}{160} = \\frac{(-9)^2}{40} + \\frac{(9)^2}{160} = 2.025 + 0.50625 = 2.53125$\n\n## O índice de $\\chi^2$ em uma tabela de contigência\n\nNo exemplo acima, as contagens esperadas foram definidas a partir de um *modelo* que dizia que as populações rurais e urbanas se dividiam nas proporções $20\\%:80\\%$. Em uma tabela de contigência, a hipótese em verificação é a de que **não há associação entre $X$ e $Y$**. Se for assim, é esperado que as frequências conjuntas sejam *porporcionais às frequências marginais*. Vamos apresentar esta ideia utilizando uma notação geral para tabelas de contingência e, em seguida, discutir com um exemplo.\n\nA tabela @tbl-contigencia apresenta $r$ linhas por $s$ colunas com as contagens de todas as combinações dos níveis da variável $X$ (Níveis $A_{1}$ a $A_{r}$) e da variável $Y$ (Níveis $B_{1}$ a $B_{s}$). Os totais marginais de $X$ e $Y$ são expressos respectivamente na última coluna e na última linha.\n\n|X ⟍ Y            |$B_{1}$  |  $B_{2}$|$\\cdots$| $B_{j}$ |$\\cdots$|$B_{s}$|Totais em $X$|\n|:---              |:---:   | :---:  |:---:   |:---:   |:---:   |:---:   |:---:        |\n| $A_{1}$          |$n_{11}$|$n_{12}$|$\\cdots$|$n_{1j}$|$\\cdots$|$n_{1s}$|$n_{1.}$     |\n| $A_{2}$          |$n_{21}$|$n_{22}$|$\\cdots$|$n_{2j}$|$\\cdots$|$n_{2s}$|$n_{2.}$     |\n| $\\vdots$         |$\\vdots$|$\\vdots$|$\\vdots$|$\\vdots$|$\\vdots$|$\\vdots$|$\\vdots$     |\n| $A_{i}$          |$n_{i1}$|$n_{i2}$|$\\cdots$|$n_{ij}$|$\\cdots$|$n_{is}$|$n_{i.}$     |\n| $\\vdots$         |$\\vdots$|$\\vdots$|$\\vdots$|$\\cdots$|$\\cdots$|$\\vdots$|$\\vdots$     |\n| $A_{r}$          |$n_{r1}$|$n_{r2}$|$\\cdots$|$n_{rj}$|$\\cdots$|$n_{rs}$|$n_{r.}$     |\n|**Totais em $Y$** |$n_{.1}$|$n_{.2}$|$\\cdots$|$n_{.j}$|$\\cdots$|$n_{rs}$|$n$          |\n\n: Representação de uma tabela de contigência. {#tbl-contigencia}\n\nSob a hipótese de **não-associação** entre $X$ e $Y$ teremos que:\n\n$\\frac{n_{i1}}{n_{.1}} = \\frac{n_{i2}}{n_{.2}} = \\cdots = \\frac{n_{is}}{n_{.s}} = \\frac{n_{i.}}{n}$\n\ne assim:\n\n$\\frac{n_{ij}}{n_{.j}} = \\frac{n_{i.}}{n}$\n\nDeste modo:\n\n$n_{ij}^{e} = \\frac{n_{i.} \\times n_{.j}}{n}$\n\n:::{.callout-note}\n## Observações\n\nA notação $n_{ij}^{e}$ está sendo utilizada para denotar que a expressão acima determina a contagem de cada célula da tabela **sob a hipótese de não associação** e portanto, se refere ao **valor esperado** de $n_{ij}$.\n\n:::\n\nTendo definido os valores esperados em uma tabela de contingência de $r \\times s$, o $\\chi^2$ é dado por:\n\n$$\\chi^2 = \\sum_{i=1}^{r}\\sum_{j=1}^{s}\\frac{(n_{ij} - n_{ij}^{e})^2}{n_{ij}^{e}}$$\n\n**Retornando ao exemplo das entrevistas**\n\nA tabela de contingência contendo os dados **observados** do início do capítulo pode ser escrita como:\n\n|                |Não-Residente      |Residente         |Total Opinião     |\n|---             |---               |---               |---               |\n|A favor         |81    |63    |144|\n|Contra          |36    |20    |56|\n|Total Moradia   |117|83|200    |\n\n: Resultados das entrevistas dos 200 munícipies. {#tbl-contigencia-municipies}\n\nOs Valores esperados na linha $i$ e coluna $j$ são:\n\n+ Linha $1$ - Coluna $1$ (`Não-Residente` - `A favor`):\n\n$n_{ii}^{e} = \\frac{n_{1.} \\times n_{.1}}{n} =  \\frac{144 \\times 117}{200} = 84.24$\n\n+ Linha $1$ - Coluna $2$ (`Residente` - `A favor`):\n\n$n_{ii}^{e} = \\frac{n_{1.} \\times n_{.2}}{n} =  \\frac{144 \\times 83}{200} = 59.76$\n\n+ Linha $2$ - Coluna $1$ (`Não-Residente` - `Contra`):\n\n$n_{ii}^{e} = \\frac{n_{2.} \\times n_{.1}}{n} =  \\frac{56 \\times 117}{200} = 32.76$\n\n+ Linha $2$ - Coluna $2$ (`Residente` - `Contra`):\n\n$n_{ii}^{e} = \\frac{n_{2.} \\times n_{.2}}{n} =  \\frac{56 \\times 83}{200} = 23.24$\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nDe modo que a tabela com os valores **esperados** será:\n\n|                |Não-Residente         |Residente            |Total Opinião     |\n|---             |---                   |---                   |---               |\n|A favor         |84.24    |59.76    |144|\n|Contra          |32.76    |23.24    |56|\n|Total Moradia   |117|83|200    |\n\n: Valores esperados na hipótese de **não-associação** entre `Opiniao` e locals de `Moradia` dos 200 munícipies entrevistados. {#tbl-contigencia-municipies-esperado}\n\nFinalmente, o valor de $\\chi^2$ pode ser calculado por:\n\n$\\chi^2 = \\frac{(81 - 84.24)^2}{84.24} + \\frac{(36 - 32.76)^2}{84.24} + \\frac{(63 - 59.76)^2}{84.24} + \\frac{(20 - 23.24)^2}{84.24} = 1.072$\n\n## Valores de $\\chi^2$ quando existe associação\n\nO valor de $\\chi^2$ será zero somente se os valores observados forem **exatamente** iguais aos valores esperados. Pequenas discrepâncias irão gerar valores de $\\chi^2$ acima de zero, que se tornarão mais altos à medida que aumentam as diferenças entre $n_{ij}$ e $n_{ij}^e$.\n\n:::{.callout-note}\n## Quantificando as associações\n\nAbaixo estão diferentes exemplos em que existe associação entre `Opinião` e `Moradia`. Compare os valores e os gráficos abaixo aos que fizemos no exemplo do capítulo  e veja que todos os valores de $\\chi^2$ são mais elevados.\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](biquali_files/figure-html/unnamed-chunk-19-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\n\n____\n\n+ Tente aplicar a fórmula do $\\chi^2$ para chegar aos resultados apresentados em cada exemplo.\n\n:::\n\n## Variações do índice de $\\chi^2$\n\nO valor de $\\chi^2$ aumenta com o tamanho da amostra, o que torna difícil comparações entre diferentes estudos. Para corrigir este efeito existe o **coeficiente de contigência de Pearson ($C$)** que é baseado no resultado de $\\chi^2$\n\n$$C = \\sqrt{\\frac{\\chi^2}{\\chi^2 + n}}$$\n\nem que $n$ é o tamanho da amostra. \n\nO valor máximo de $C$ depende do número de linhas ($r$) e de colunas ($s$) na tabela de contingêcia. Podemos definir um coeficiente que esteja limitado entre $0$ e $1$:\n\n$$T = \\sqrt{\\frac{\\frac{\\chi^2}{n}}{(r-1) \\times (s-1)}}$$\nO valor $T = 0$ ocorre quando **não há** associação ($\\chi^2 = 0$) e o valor máximo de $T = 1$ só será atingido se houver associação e $r = s$\n\n\n## Obtendo o índice de $\\chi^2$ de uma tabela de dados\n\nA função para o cálculo do $\\chi^2$ no R é `chisq.test` e pode ser utilizada a partir da tabela de contigência gerada pela função `table`:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntcont = table(mun$Opiniao, mun$Moradia)\nchisq.test(tcont)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  tcont\nX-squared = 0.76697, df = 1, p-value = 0.3812\n```\n\n\n:::\n:::\n\n\n\n\nO resultado mostra o o valor de $\\chi^2$ calculado (`X-squared`) e outras duas quantias denominadas de **graus de liberdade** (`df`) e **valor de p** (`p-value`),  tópicos abordados em *inferência estatística*.\n\nNote que o resultado é diferente do que obtivemos neste capítulo. Isto ocorre pois, por padrão, a função utiliza a [correção de Yates](https://en.wikipedia.org/wiki/Yates%27s_correction_for_continuity){target=\"_blank\"}, em que $\\chi_{Yates}^{2}$ é calculado por:\n\n$$\\chi_{Yates}^{2} = \\sum_{i=1}^{r}\\sum_{j=1}^{s}\\frac{(|n_{ij} - n_{ij}^{e}| - 0,5)^2}{n_{ij}^{e}}$$\n\nO termo $|n_{ij} - n_{ij}^{e}|$ se refere ao módulo da distância entre os valores observados e calculados. \n\nSe quisermos obter exatamente os resultados descritos no exemplo deste capítulo, basta fazermos:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(tcont, correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tPearson's Chi-squared test\n\ndata:  tcont\nX-squared = 1.0724, df = 1, p-value = 0.3004\n```\n\n\n:::\n:::\n",
    "supporting": [
      "biquali_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}