{
  "hash": "dc6349f87c67272f6d6f8fee6169894e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Comparando médias: teste t de Student\"\ndescription: \"Teste t de Student para comparação de médias, abrangendo uma amostra, grupos independentes e medidas pareadas.\"\nCategories: [\n          \"Inferência estatística\",\n          \"Teste de hipóteses\",\n          \"Comparação de médias\"\n        ]\n\nimage: \"images/teste-t.jpg\"\nexecute:\n  echo: true\n  warning: false\n  include: true\n  message: false\n---\n\n\n\n\n:::{.callout-tip collapse=\"true\"}\n## Pacotes, funções e base de dados utilizadas no capítulo\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gt)\n```\n:::\n\n\n\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nO modelo normal de probabilidades não é a melhor aproximação para a distribuição das médias amostrais quando não conhecemos $\\mu$ e $\\sigma$ e/ou quando o tamanho amostral $n$ é pequeno. Nesta situação, a **distribuição t de Student** é mais apropriada para o cálculo do intervalo de confiança. Da mesma forma, o **teste $Z$** assume que a distribuição das médias amostrais é normalmente distribuída e que a variância populacional $\\sigma$ seja conhecida, uma informação que não temos na prática científica.\n\n\nO **teste t de Student** é utilizado em substituição ao **teste $Z$** quando $\\sigma$ é desconhecido e/ou o tamanho amostral é pequeno. A lógica do teste é a mesma apresentada discutida no teste $Z$, porém estabelece que a distribuição das médias  amostrais é melhor descrita pela distribuição $t$ e não pela distribuição normal.\n\n::: {#fig-Z_vs_T_distribution}\n\n![](images/Z-vs-T-distribution.png)\n\nTeste Z versus teste t. Estatística do teste e distribuição de probabilidades.\n:::\n\n\n## Teste t para uma média populacional\n\nConsidere um exemplo simples. Dados do Banco Central do Brasil dizem que moedas de $R\\$ 0,10$ da segunda geração pesam 4.8 gramas. Você tem $8$ moedas no bolso e resolve testar essa afirmação pesando cada moeda. Os pesos obtidos são: $X = 5.1, 5, 4.8, 5, 5, 4.9, 4.9, 4.7$.\n\nInicialmente, devemos estabelecer nossa hipótese nula ($H_0$), nossa hipótese alternativa ($H_a$) e o nível se significância $\\alpha$. Iremos estabelecer $\\alpha = 0,05$ e as hipóteses como:\n\n$H_0: \\mu = 4.8$ gramas\n\n$H_a: \\mu \\ne 4.8$ gramas\n\nComo não conhecemos $\\sigma$ e temos uma amostra pequena, a posição das médias amostrais seguirá uma distribuição $t$ de Student e a estatística do teste será:\n\n$$t = \\frac{\\overline{X} - \\mu}{s_{\\overline{X}}}$$\n\nsendo o erro padrão amostral obtido por:\n\n$$s_{\\overline{X}} = \\frac{s}{\\sqrt{n}}$$\n\nO cálculo de $t$ é muito similar ao escore $Z$. No entanto, substituímos $\\sigma$ por $s$. As distribuições de $t$ e de $Z$ são muito similares. Entretanto, para amostras pequenas e quando $\\sigma$ é desconhecido, a curva de $t$ nos fornece uma melhor estimativa das probabilidades associadas a distribuição das médias amostrais.\n\nPara este exemplo, temos uma amostra de tamanho $n = 8$ com média $\\overline{X} = 4.925$g e desvio padrão $s = 0.13$g. O valor de $t$ pode ser calculado por:\n\n$$t_{c} = \\frac{\\overline{X} - \\mu}{s_{\\overline{X}}} = \\frac{\\overline{X} - \\mu}{\\frac{s}{\\sqrt{n}}} = \\frac{4.925  - 4.8}{\\frac{0.13}{\\sqrt{8}}} = 2.76$$\n\nAssim como fizemos para a distribuição $Z$, devemos encontrar a probabilidade de obtermos um valor tão ou maior que o módulo de $t_c$. Na figura abaixo, nosso resultado fica:\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Valor de p associado ao resultado do teste t.](teste-t_files/figure-html/fig-limite-rej-t-1.png){#fig-limite-rej-t width=768}\n:::\n:::\n\n\n\n\nA probabilidade de encontrarmos um valor de $t_c$ tão ou mais extremo segundo a hipótese nula foi de $p = 0.028$. Uma vez que este valor é **menor** que o nível crítico $\\alpha = 0,05$, concluímos que existe evidência suficiente para **rejeitar** $H_0$ e **aceitar** a hipótese alternativa de que as moedas de $10$ centavos **não** provém de uma população estatística com $\\mu = 4,8$ gramas. Nossa conclusão é portanto, que as moedas de $R\\$ 0,10$ são mais **pesadas** que $4,8$ gramas.\n\n::: {.callout-note}\n\n# Terste t no R\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(X, mu = 4.8)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tOne Sample t-test\n\ndata:  X\nt = 2.7584, df = 7, p-value = 0.02816\nalternative hypothesis: true mean is not equal to 4.8\n95 percent confidence interval:\n 4.817844 5.032156\nsample estimates:\nmean of x \n    4.925 \n```\n\n\n:::\n:::\n\n\n\n\n___\n\nNos comandos acima, $X$ é a amostra e o argumento ```mu``` representa a expectativa sobre a média populacional *segundo $H_0$*. Como resultados temos:\n\n+ a indicação de que fizemos um *teste $t$* para uma amostra: ```One Sample t-test```;\n\n+ o valor de $t$ calculado: ```t = 2.7584 ```;\n\n+ os graus de liberdade: ```df = 8 - 1 = 7 ```; e \n\n+ o valor de ```p = 0.028 ```. \n\nA saída da função apresenta ainda o valor da média amostral ($\\overline{X} = 4.925$) e o intervalo de confiança a $95\\%$ (``` 4.817844 - 5.032156 ```).\n\n:::\n\n## Graus de liberdade\n\nA distribuição $t$ como várias outras distribuições amostrais utilizadas em inferência estatística, muda seu formato em função do que chamamos de **graus de liberdade** ($gl$). Os graus de liberdade têm relação com o tamanho amostral. No caso do teste $t$ para $1$ amostra, esta relação é simplesmente: $gl = n-1$. \n\nÀ medida que os graus de liberdade aumentam, o formato da distribuição $t$ se assemelha ao formato da distribuição Normal padronizada. De fato, para graus de liberdades altos (ex. $n \\ge 30$), os formatos das distribuições $Z$ e $t$ são praticamente indistinguíveis. Na prática, isto faz que as distribuição $Z$ **raramente** seja utilizada.\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Função de densidade de t para diferentes graus de liberdade.](teste-t_files/figure-html/fig-dist-t-gl-1.png){#fig-dist-t-gl width=768}\n:::\n:::\n\n\n\n\n\n## Probabilidades no teste $t$ de Student: a tabela $t$\n\nA rejeição uo aceitação da hipótese nula em um teste $t$ pode ser feita por meio da obtenção do *valor de p* ou pela comparação do $t$ calculado com valores críticos de referência para determinado nível de significância. O primeiro caso foi o que apresentamos acima e depende de um software estatístico para obtermos valores exatos de $p$. O segundo caso, pode ser feito com auxílio da Tabela $t$, em que limites críticos de $t$ são disponibilizados para diferentes níveis de significância e graus de liberdade.\n\nAtualmente, o uso da tabela $t$ têm finalidade em grande parte didática e, por este motivo, vamos apresentá-lo aqui rapidamente. No entanto, fora da sala de aula, o teste $t$ será invariavelmente conduzido por meio de um software estatístico este método que permitirá a obtenção do valor exato de $p$.\n\nNa <a href=\"https://github.com/FCopf/datasets/blob/main/Tabela_t.pdf\" target=\"_blank\">Tabela t</a>, a primeira coluna mostra os *graus de liberdade* de $1$ a $120$. O cabeçalho da tabela de $90\\%$ a $0,1\\%$ mostra a área na distribuição de $t$ nas caldas inferior e superior.\n\nVamos retornar ao exemplo da moedas de $R\\$0,10$ para exemplificar sua utilização. Neste exemplo a tinhamos $8$ ($gl = 7$ graus de liberdade) e o teste foi feito com $\\alpha =0,05$. Se buscarmos na linha $gl = 7$ e a coluna $5\\%$ ($\\alpha = 0,05$), encontraremos o valor $t = 2,3646$. Este é o chamado $t$ **crítico** ($t_{crítico}$). Acima deste valor e abaixo de sua contraparte negativa temos exatamente $5\\%$ da área na disribuição $t$. Deste modo, qualquer valor calulado **maior** que $t_{crítico}$ estará mais para a extremidade da distribuição e consequentemente estará associado a **menores** valores de probabilidade. Neste sentido:\n\n> $t_{calculado} \\ge t_{crítico}$ leva a *rejeição* de $H_0$\n\n> $t_{calculado} < t_{crítico}$ leva a *aceitação* de $H_0$\n\nO resultado do teste estatístico em nosso exemplo foi $t_c = 2.76$ que é **maior** que $2,3646$. Isto nos leva à mesma decisão anterior (**rejeitar** $H_0$), ainda que por meio da tabela $t$ não tenhamos o valor exato de probabilidade.\n\n\n## Teste t para comparação de duas médias independentes\n\nO que vimos no teste $t$ para uma amostra pode ser facilmente extendido para testarmos a diferenças entre duas amostras. \n\nOs dados abaixo mostram o tempo de coagulação sanguínea (em minutos) em ratos machos adultos tratados com dois tipos de drogas, retirado do livro Biostatistical Analysis [@zar2010biostatistical], pp. 130-134.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nra <- data.frame(Droga = factor(c(rep(\"Droga A\", 6), rep(\"Droga B\",7))),\n                Tempo = c(8.8, 8.4, 7.9, 8.7, 9.1, 9.6, \n                          9.9, 9.0, 11.1, 9.6, 8.7, 10.4, 9.5))\n```\n:::\n\n::: {#tbl-coagulacao .cell tbl-cap='Tempo de coagulação sanguínea (em minutos) para dois tipos de drogas.'}\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dxhsydxbtw\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dxhsydxbtw table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dxhsydxbtw thead, #dxhsydxbtw tbody, #dxhsydxbtw tfoot, #dxhsydxbtw tr, #dxhsydxbtw td, #dxhsydxbtw th {\n  border-style: none;\n}\n\n#dxhsydxbtw p {\n  margin: 0;\n  padding: 0;\n}\n\n#dxhsydxbtw .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dxhsydxbtw .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dxhsydxbtw .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dxhsydxbtw .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dxhsydxbtw .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dxhsydxbtw .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dxhsydxbtw .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dxhsydxbtw .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dxhsydxbtw .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dxhsydxbtw .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dxhsydxbtw .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dxhsydxbtw .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dxhsydxbtw .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dxhsydxbtw .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dxhsydxbtw .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dxhsydxbtw .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dxhsydxbtw .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dxhsydxbtw .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dxhsydxbtw .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxhsydxbtw .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dxhsydxbtw .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dxhsydxbtw .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dxhsydxbtw .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxhsydxbtw .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dxhsydxbtw .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dxhsydxbtw .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dxhsydxbtw .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxhsydxbtw .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dxhsydxbtw .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dxhsydxbtw .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dxhsydxbtw .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dxhsydxbtw .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dxhsydxbtw .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxhsydxbtw .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dxhsydxbtw .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dxhsydxbtw .gt_left {\n  text-align: left;\n}\n\n#dxhsydxbtw .gt_center {\n  text-align: center;\n}\n\n#dxhsydxbtw .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dxhsydxbtw .gt_font_normal {\n  font-weight: normal;\n}\n\n#dxhsydxbtw .gt_font_bold {\n  font-weight: bold;\n}\n\n#dxhsydxbtw .gt_font_italic {\n  font-style: italic;\n}\n\n#dxhsydxbtw .gt_super {\n  font-size: 65%;\n}\n\n#dxhsydxbtw .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dxhsydxbtw .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dxhsydxbtw .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dxhsydxbtw .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dxhsydxbtw .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dxhsydxbtw .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dxhsydxbtw .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dxhsydxbtw .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dxhsydxbtw div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout:fixed;width:0px;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:200px;\"/>\n    <col style=\"width:400px;\"/>\n  </colgroup>\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Droga\">Droga</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Tempo\">Tempo</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga A</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">8.80</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga A</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">8.40</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga A</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">7.90</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga A</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">8.70</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga A</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">9.10</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga A</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">9.60</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga B</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">9.90</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga B</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">9.00</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga B</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">11.10</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga B</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">9.60</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga B</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">8.70</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga B</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">10.40</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga B</td>\n<td headers=\"Tempo\" class=\"gt_row gt_right\">9.50</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nNosso objetivo é testar se as duas drogas resultam, em média, no mesmo tempo de coagulação. Inicialmente, vamos fazer um gráfico de dispersão para verificar a distribuição do tempo de coagulação para cada droga.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(ra, aes(y = Tempo, x = Droga)) +\n  geom_boxplot() +\n  geom_point(col = 2, size = 3) +\n  labs(y = 'Tempo de coalgulação (min)', x = '') +\n  theme_classic(base_size = 15)\n```\n\n::: {.cell-output-display}\n![Distribuição do tempo de coagulação sanguínea (em minutos) para dois tipos de drogas.](teste-t_files/figure-html/fig-bx-coagulacao-1.png){#fig-bx-coagulacao width=576}\n:::\n:::\n\n\n\n\nAs médias, desvios padrões e tamanhos amostrais de cada grupo são:\n\n\n\n\n::: {#tbl-coagulacao-summary .cell tbl-cap='Tempo de coagulação sanguínea (em minutos) para dois tipos de drogas.'}\n\n```{.r .cell-code  code-fold=\"true\"}\nra_m = ra |> \n    group_by(Droga) |> \n    summarize('Tempo médio' = round(mean(Tempo),2), \n              Desvio = round(sd(Tempo),2), n = n() )\n\nra_m |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"fzvbcjfbrz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fzvbcjfbrz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fzvbcjfbrz thead, #fzvbcjfbrz tbody, #fzvbcjfbrz tfoot, #fzvbcjfbrz tr, #fzvbcjfbrz td, #fzvbcjfbrz th {\n  border-style: none;\n}\n\n#fzvbcjfbrz p {\n  margin: 0;\n  padding: 0;\n}\n\n#fzvbcjfbrz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fzvbcjfbrz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fzvbcjfbrz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fzvbcjfbrz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fzvbcjfbrz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fzvbcjfbrz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fzvbcjfbrz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fzvbcjfbrz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fzvbcjfbrz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fzvbcjfbrz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fzvbcjfbrz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fzvbcjfbrz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fzvbcjfbrz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fzvbcjfbrz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fzvbcjfbrz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fzvbcjfbrz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fzvbcjfbrz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fzvbcjfbrz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fzvbcjfbrz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzvbcjfbrz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fzvbcjfbrz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fzvbcjfbrz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fzvbcjfbrz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzvbcjfbrz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fzvbcjfbrz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fzvbcjfbrz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fzvbcjfbrz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzvbcjfbrz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fzvbcjfbrz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fzvbcjfbrz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fzvbcjfbrz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fzvbcjfbrz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fzvbcjfbrz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzvbcjfbrz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fzvbcjfbrz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fzvbcjfbrz .gt_left {\n  text-align: left;\n}\n\n#fzvbcjfbrz .gt_center {\n  text-align: center;\n}\n\n#fzvbcjfbrz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fzvbcjfbrz .gt_font_normal {\n  font-weight: normal;\n}\n\n#fzvbcjfbrz .gt_font_bold {\n  font-weight: bold;\n}\n\n#fzvbcjfbrz .gt_font_italic {\n  font-style: italic;\n}\n\n#fzvbcjfbrz .gt_super {\n  font-size: 65%;\n}\n\n#fzvbcjfbrz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fzvbcjfbrz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fzvbcjfbrz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fzvbcjfbrz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fzvbcjfbrz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fzvbcjfbrz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fzvbcjfbrz .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#fzvbcjfbrz .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#fzvbcjfbrz div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Droga\">Droga</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Tempo-médio\">Tempo médio</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Desvio\">Desvio</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga A</td>\n<td headers=\"Tempo médio\" class=\"gt_row gt_right\">8.75</td>\n<td headers=\"Desvio\" class=\"gt_row gt_right\">0.58</td>\n<td headers=\"n\" class=\"gt_row gt_right\">6</td></tr>\n    <tr><td headers=\"Droga\" class=\"gt_row gt_center\">Droga B</td>\n<td headers=\"Tempo médio\" class=\"gt_row gt_right\">9.74</td>\n<td headers=\"Desvio\" class=\"gt_row gt_right\">0.82</td>\n<td headers=\"n\" class=\"gt_row gt_right\">7</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nPara testarmos se as médias dos grupos provém de populações estatísticas com diferentes $\\mu's$ devemos estabelecer nosso nível de significância (por exemplo $\\alpha = 0.05$) as hipoteses estatísticas:\n\n$H_0: \\mu_A = \\mu_B$ gramas\n\n$H_a: \\mu_A \\ne \\mu_B$ gramas\n\n:::{.callout-note}\n\n# Teste de homogeneidade de variâncias\n\nUm dos pressupostos do teste t que apresentaremos a frente é de que as populações que serão comparadas têm a mesma variância $\\sigma^2$. Devemos portanto testar o pressuposto de **homogeneidade de variâncias** que pode ser realizado com o teste de razão de variâncias.\n\nNo R fazemos o teste de homogeneidade de variâncias com o comando abaixo.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvar.test(ra$Tempo ~ ra$Droga)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tF test to compare two variances\n\ndata:  ra$Tempo by ra$Droga\nF = 0.50633, num df = 5, denom df = 6, p-value = 0.4722\nalternative hypothesis: true ratio of variances is not equal to 1\n95 percent confidence interval:\n 0.08456359 3.53301988\nsample estimates:\nratio of variances \n           0.50633 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nNo teste acima, $F_{calculado} = 0.51$ e $p = 0.472$. Assumindo um $\\alpha = 0,05$, concluímos que **não há evidências** para rejeitar a hipótese de homogeneidade e que assumimos que as duas populações têm a mesma variância. Deste modo podemos continuar com o teste t.\n\n:::\n\n\n\n\nO teste t para duas amostras é calculado por:\n\n$$t = \\frac{(\\overline{X_A} - \\mu_A) - (\\overline{X_B} - \\mu_B)}{s_{\\overline{X_A}-\\overline{X_B}}}$$\n\nAssumindo a hipotese nula em que $\\mu_A = \\mu_B$ a expressão fica\n\n$$t = \\frac{\\overline{X_A} - \\overline{X_B}}{s_{\\overline{X_A}-\\overline{X_B}}}$$\n\nem que a quantia $s_{\\overline{X_A}-\\overline{X_B}}$ é calculada por:\n\n$$s_{\\overline{X_A}-\\overline{X_B}} = \\sqrt{\\frac{s^2_{p}}{n_1} + \\frac{s^2_{p}}{n_2}}$$\n\n\n$s_p$ é denominada de **variância conjunta** calculada por\n\n$$s^2_p = \\frac{(n_1 - 1) \\times s^2_1 + (n_2 - 1) \\times s^2_2}{(n_1 - 1) + (n_2 - 1)}$$\n\nPara este exemplo, \n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n$s_p = 0.52$\n\ne\n\n$s_{\\overline{X_A}-\\overline{X_B}} =  0.4$\n\nO valor de t calculado é:\n\n$t_c =  -2.476$\n\nNa distribuição t, a probabilidade de encontrar valores tão ou mais extremos que 2.476 é de $p = 0.031$.\n\nPortanto:\n\n$P(|t| \\ge 2.476) \\le 0.05$\n\nUma vez que a probabilidade associada ao valor de $t$ é menor que o nível de significância, **rejeitamos** $H_0$ e assumimos que os tempos médios de coagulação **são diferentes**. Ao avaliar as média amostrais $\\overline{X}_A$ e $\\overline{X}_B$, concluímos que **a droga $A$** resulta, em média, em tempos menores de coagulação.\n\n___\n\n:::{.callout-note}\n# Vídeo-aulas\n\n<iframe\n  style=\"width:100%; aspect-ratio:16/9;\"\n  src=\"https://www.youtube-nocookie.com/embed/Mu4QQr5ud58\"\n  title=\"YouTube video player\"\n  frameborder=\"0\"\n  allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\n  allowfullscreen>\n</iframe>\n\n:::\n\n",
    "supporting": [
      "teste-t_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}