project:
  type: website

lang: pt

website:
  title: "Métodos em Estatística e Análise de Dados"
  description: "Conteúdos introdutórios e intermediários sobre estatística aplicada e análise de dados."
  site-url: "https://github.com/FCopf/MEAD"

  repo-url: https://github.com/FCopf/MEAD
  open-graph: true

  # Navbar configuration
  navbar:
    background: "#3b8170"
    search: true
    logo: "images/logo_white.png"
    right: # Content on the right https://github.com/FCopf/MEADhe navbar
       - icon: github
         href: https://github.com/FCopf/MEAD
         text: "GitHub"

# Global format configuration
format:
  html:
    theme:
      light: zephyr
    css: styles/custom.css
    toc: true
    number-sections: true
    code-copy: true
    code-overflow: wrap

# Configura projeto para ser executado apenas localmente
execute:
  freeze: auto

bibliography: references.bib