{
  "hash": "7cfcbad96ff535a5c175f4b2ebce882a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Amostrando uma população estatística\"\ndescription: \"Métodos de amostragem aleatória simples, estratificada e sistemática, destacando o erro amostral e a acurácia das estimativas.\"\nCategories: [\n          \"Estatística\",\n          \"Amostragem\"\n        ]\nimage: \"images/tipos-amostragem.jpg\"\nexecute:\n  echo: true\n  warning: false\n  include: true\n  message: false\n---\n\n\n\n\n:::{.callout-tip collapse=\"true\"}\n## Pacotes, funções e base de dados utilizadas no capítulo\n\nPacotes:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(patchwork)\nlibrary(gt)\nlibrary(knitr)\n```\n:::\n\n\n\n:::\n\nO objetivo da amostragem é descrever características da **população estatística** por meio de características da **amostra**. Por exemplo, em um estudo sobre o tamanho do pescado em uma área de pesca, a população estatística são os comprimentos de todos os peixes que podem ser pescados na região. A população estatística pode ser descrita por **parâmetros** que representam medidas de centro como o comprimento médio ($\\mu$), ou por medidas de variação como o desvio padrão ($\\sigma$), que representam o grau de dispersão das unidades amostrais ao redor da média. Se amostramos **n** elementos desta população, a média amostral ($\\overline{X}$) e o desvio padrão amostral ($s$) dos diâmetros serão os estimadores destas características.\n\nDependendo da questão envolvida e do conhecimento prévio sobre a população, diferentes métodos de amostragem são apropriados. A  **teoria da amostragem** é a área da ciência que estuda estes métodos. Neste capítulo vamos discutir três tipos de amostragem: **aleatória simples**, **estratificada** e **sistemática**.\n\n## Amostragem aleatória simples\n\nÉ aquela em que cada elemento da população tem a mesma probabilidade de ser selecionado para compor a amostra. Se a população consiste de $1000$ elementos, cada um terá uma probabilidade de $\\frac{1}{1000}$ de ser escolhido. Isto isenta o pesquisador de tomar qualquer decisão com base em julgamentos pré-concebidos, sobre quais elementos devem ou não compor a amostra.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1)\npop = c(3, 10, 14, 19, 27, 28, 29, 41, 42, 43)\nN = length(pop)\nAm1 = sort(pop)[1:5]\nset.seed(2)\nAm2 = sample(pop, size = 5, replace = F)\n```\n:::\n\n\n\n\nSuponha uma população hipotética de somente $10$ elementos: \n\n**População**: 3, 10, 14, 19, 27, 28, 29, 41, 42, 43\n\nEm uma amostra aleatória simples de cinco elementos, qualquer combinação destes $10$ elementos é **igualmente provável**. Se por puro acaso sortearmos uma amostra aleatória contendo os cinco menores valores da população:\n\n**Amostra 1**: 3, 10, 14, 19, 27\n\nA amostra seria **tão aleatória** e válida do ponto de vista estatístico quanto qualquer outra como:\n\n**Amostra 2**: 27, 28, 42, 3, 43\n\nIsto significa que uma amostra aleatória pode não ser **necessariamente** representativa da população. Amostras pequenas por exemplo, têm uma chance maior de selecionar apenas valores extremos, ou seja, os maiores ou menores elementos da população. A média amostral ($\\overline{X}$) calculada para estas amostras estará distante da média populacional ($\\mu$). \nNo entanto, a importância central da amostragem aleatória em estatística está no fato de que a aleatoriedade produz, **em média**, amostras representativas da população. Deste modo, é esperado que na maioria das vezes, uma amostra aleatória gere médias amostrais próximas à média populacional. Por este motivo, é fundamental prezar pela aleatoriedade no processo amostral, pois de outro modo não poderemos garantir que a inferência seja válida com base nas leis de probabilidade. \n\nO modo mais direto de se obter uma amostra aleatória é por meio de sorteio. Após atribuir números de 1 a $N$ a cada unidade amostral, estas unidades são sorteadas até que seja atingido o tamanho $n$ desejado. Na prática, nem sempre é simples, ou mesmo possível obter uma amostra aleatória nestes moldes. Não seria possível enumerar todos os peixes de uma região para, após um sorteio, tomar as medidas somente dequeles selecionados. Entretanto, se empregarmos métodos de captura em que indivíduos de todos os tamanhos sejam igualmente sujeitos a serem capturados poderíamos no *aproximar* do que seria uma amostra verdsadeiramente aleatória. Outras dificuldades práticas surgiriam neste estudo como por exemplo: garantir acesso irrestrito à toda a área de ocorrência da espécie, tempo disponível para percorrer a toda região. Questões como estas não desmerecem o requisito básico de se obter uma amostra aleatória, mas devem nos auxiliar a decidir como conciliar a prática experimental com a necessidade de garantirmos uma amostra aleatória.\n\n## Amostragem aleatória estratificada\n\nSe tivermos algum conhecimento prévio de como a população está estruturada, a amostra aleatória simples, embora não esteja incorreta, pode não ser a estratégia mais eficiente do ponto de vista estatístico. Se for possivel identificar **estratos** ou **subgrupos** dentro da população, podemos conduzir uma **amostragem aleatória estatificada**. \n\nVoltemos ao exemplo do comprimento do pescado. Suponha que existam duas áreas de ocorrência da espécie. Uma delas sujeita a intensa atividade pesqueira e outra sendo uma área protegida. Poderíamos supor que na área protegida estejam os maiores indivíduos, justamente porque nesta área não há atividade de pesca (que em geral busca indivíduos maiores). Dizemos que os comprimentos em cada uma das duas regiões compõem estratos da população estatística.\n\nNesta situação, uma amostra puramente aleatória  **sem considerar** a existência dos dois estratos pode fazer com que, puramente ao acaso, um deles se torne mais representados na amostra. Se por exemplo da maioria dos pontos selecionados estiverem na região intensamente pescada, o comprimento médio da amostra ($\\overline{X}$) tenderá a ficar consistentemente abaixo de $\\mu$. A chance disto ocorrer se torna maior principalmente se o tamanho amostral for pequeno. \n\nEntretanto, se a seleção dos indivíduos foi feita por meio de sorteio, o simples fato de observarmos este padrão não seria por si só justificativa para refarzermos a amostra. O ponto relevante aqui é que em uma amostra aleatória simples, estes extremos indesejáveis (um estrato mais representado que outro) são mais prováveis de acontecer.\n\nSe temos conhecimento da existência dos dois estratos portanto, a amostragem aleatória **estratificada** seria a mais indicada. Neste tipo de amostragem, o esforço amostral é subdividido entre os estratos. O tamanho amostral em cada estrato será o mesmo, ou **proporcional** ao seu tamanho. Uma vez definirmos os tamanhos amostrais que será aplicado aos estratos, as unidades são selecionadas por meio de uma amostragem aleatória simples em cada um. \n\nA amostragem aleatória estratificada garante que **todos** os estratos estejam presentes na amostra conforme sua representatividade na população. Ao fazer isto, as estimativas da amostra tenderão a se concentrar mais próximas ao parâmetro da população. Deste modo, quando os estratos são identificados **corretamente**, a principal vantagem da amostra aleatória estratificada sobre a amostra aleatória simples está em aumentar a **precisão** das estimativas. Mais a frente iremos discutir os conceitos de precisão e acurácia e relacioná-los com as estratégias amostrais discutidas aqui.\n\n## Amostragem sistemática\n\nEm uma amostragem sistemática o pesquisador escolhe um elemento inicial e toma medidas a cada $k$ ocorrências, seguindo a ordem de observação. No caso do comprimento de pescado, para facilitar a tomada de dados, o pesquisador pode medir o primeiro peixe coletado e, em seguida, medir os peixes em intervalos regulares, por exemplo a cada $10$ observados.\n\nA escolha da amostragem sistemática ao invés de uma amostragem aleatória simples, deve-se à sua praticidade. Se a característica de interesse das unidades amostrais estiver disposta de forma aleatória ao longo da sequência escolhida, a amostragem aleatória e sistemática irão gerar resultados similares. Na maioria dos casos, é isto que o pesquisador assume (ainda que implicitamente) quando opta por uma amostragem sistemática.\n\n\n## Erro amostral, acurácia e precisão\n\nComo as estimativas são obtidas de um subconjunto da população (a amostra), é regra que o resultado obtido de uma amostra aleatória particular, não será igual ao verdadeiro valor da população (o parâmetro), embora exista uma grande probabilidade estar próximo. \n\n+ **Erro amostral**: é a diferença entre uma estimativa em particular e o parâmetro na população e portanto, é inerente à variabilidade do processo de amostragem. Suponha que, puramente ao acaso, a amostra inclua os menores elementos da população. A média amostral ($\\overline{X}$) estará muito abaixo da média populacional ($\\mu$) e o erro amostral será grande. Se calcularmos a média ($\\overline{X}$) de uma amostra particular, o erro amostral será dado por:\n\n$$E = \\overline{X} - \\mu$$\n\nA estatística estuda o comportamento probabilístico dos erros amostrais. Existe também o **erro não amostral** que decorre de equívocos de amostragem, inexperiência do amostrador, falha de equipamentos, enganos no cômputo dos resultados, etc. A estatística **não lida** com este tipo de erro.\n\n+ **Acurácia**: se refere à proximidade entre o parâmetro e o estimador. Um estimador acurado é, em média, igual ao parâmetro populacional. Diferente do erro amostral, a acurácia não se refere a uma estimativa em particular, mas ao valor **esperado** do estimador, caso a amostragem fosse repetida um grande número de vezes. Um estimador não-acurado (**viciado**) resulta em valores **consistentemente** diferentes do parâmetro, podendo estar acima (**viés positivo**) ou abaixo (**viés negativo**) do valor populacional. A média aritmética amostral ($\\overline{X}$) é um estimador não-viciado da média populacional ($\\mu$) pois:\n\n$$\\mu_{\\overline{X}} = \\mu$$\n\n+ **Precisão**: tem relação com a variabilidade do estimador. Estimadores que geram estimativas similares entre si são mais precisos. Porém, se as estimativas estiverem distantes de sua média, o estimador é dito pouco preciso. **Exemplo**: Para uma população normalmente distribuída, tanto a média aritmética quanto a mediana são estimadores acurados. Entretanto, a variância da mediana é maior que da média aritmética. Dizemos portanto, que a média aritmética é um estimador mais preciso que a mediana. A precisão de um estimador é medida pelo **erro padrão da média**.\n\n$$\\sigma_{\\overline{X}} =\\frac{\\sigma}{\\sqrt{n}}$$\n\nA figura abaixo é comnmente utilizada para representar os conceitos de precição e acurácia. O centro do alvo é o valor do parâmetro populacional e os pontos em preto são as estimativas. Estimadores acurados geram, em média, estimativas ao redor do parâmetro populacional (viés $= 0$). Estimadores **não-acurados** geram, em média, valores deslocados do parâmetro populacional (viés $\\ne 0$). Estimadores precisos resultam sempre em estimativas próximas entre si, enquanto estimadores não precisos resultam em estimativas distantes umas das outras.\n\n\n::: {#fig-precis-acur}\n\n![](imgages/precisao-acuracia.png)\n\nRepresentação dos conceitos de precisão e acurácia.\n:::\n\n### Erro amostral\n\nVoltemos à nossa população fictícia com $N = 10$ elementos:\n\n**População**: 3, 10, 14, 19, 27, 28, 29, 41, 42, 43\n\nPara esta população em particular nós conhecemos a média populacional ($\\mu$ = 25.6), de modo que será possível compará-la com as estimativas amostrais.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(4)\nn = 5\nAm1 = sample(pop, size = n, replace = F)\nsomaAm1 = paste(Am1, collapse = \"+\")\nmp = round(mean(pop),1)\nmAm1 = round(mean(Am1),1)\nE1 = mAm1 - mp\n```\n:::\n\n\n\n\nVamos tomar uma amostra aleatória de tamanho $n = 5$:\n\n**Amostra 1**: $41, 14, 42, 29, 19$\n\nPara esta amostra, a média vale: $\\overline{X} =\\frac{41+14+42+29+19}{5} = 29$.\n\nOs valores $\\mu = 25.6$ e $\\overline{X} = 29$ não são idênticos, pois a amostra contém somente alguns elementos da população. A diferença entre $\\mu$ e $\\overline{X}$ é o chamamos de **erro amostral**.\n\nNeste caso, o erro amostral é:\n\n**Erro amostral 1**: $E_1 = 29  -  25.6  =  3.4$\n\nSe tomarmos outra amostra aleatória, teremos outro conjunto de unidades amostrais, e consequentemente, um $\\overline{X}$ e um erro amostral diferentes. Por exemplo:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(3)\nn = 5\nAm2 = sample(pop, size = n, replace = F)\nmAm2 = round(mean(Am2),1)\nE2 = mAm2 - mp\n```\n:::\n\n\n\n\n**Amostra 2**: $27, 29, 19, 10, 14$\n\n**Média amostral 2**: $\\overline{X_2} = 19.8$\n\n**Erro amostral 2**: $E_2 = 19.8  -  25.6  =  -5.8$\n\n\n### Acurácia\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nN = length(pop)\nn = 5\nCT = choose(N,n)\n```\n:::\n\n\n\n\nAté agora, analisamos duas amostras diferentes da população. Porém, quantas amostras distintas seriam possíveis? Para uma amostragem **sem reposição**, a teoria combinatória nos diz que são possíveis:  \n\n$${{10}\\choose{5}} = \\frac{10!}{(10-5)! \\times 5!} = 252$$\n\nformas diferentes de combinarmos $N = 10$ elementos em amostras de tamanho $n = 5$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(8)\nR = 8\nA15 = replicate(n = R, sample(pop, size = n, replace = F))\ncolnames(A15) = paste(\"A\", 1:ncol(A15), sep = \"\")\nMedias = round(apply(A15, 2, mean),2)\n```\n:::\n\n\n\n\nInicialmente vamos avaliar a questão com um número menor. Sejam por exemplo, 8 amostras tomadas aleatoriamente, gerando os resultados a seguir:\n\n\n\n\n::: {#tbl-amostr-pop .cell tbl-cap='Oito amostras de tamanho n = 5 da população estatística.'}\n\n```{.r .cell-code  code-fold=\"true\"}\nA15 |> \n  as.data.frame() |> \n  add_column('Obs' = rep('', times = nrow(A15)), .before = 'A1') |> \n  rbind(Obs = c('Médias', Medias)) |> \n  gt() |> \n  tab_style(\n    style = list(cell_fill(color = \"lightblue\")),\n    locations = cells_body(\n      rows = Obs == \"Médias\"\n    )\n  ) |> \n  cols_width(\n    everything() ~ px(150)\n  )\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xefjlcyhds\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xefjlcyhds table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xefjlcyhds thead, #xefjlcyhds tbody, #xefjlcyhds tfoot, #xefjlcyhds tr, #xefjlcyhds td, #xefjlcyhds th {\n  border-style: none;\n}\n\n#xefjlcyhds p {\n  margin: 0;\n  padding: 0;\n}\n\n#xefjlcyhds .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xefjlcyhds .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xefjlcyhds .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xefjlcyhds .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xefjlcyhds .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xefjlcyhds .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xefjlcyhds .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xefjlcyhds .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xefjlcyhds .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xefjlcyhds .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xefjlcyhds .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xefjlcyhds .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xefjlcyhds .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xefjlcyhds .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xefjlcyhds .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xefjlcyhds .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xefjlcyhds .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xefjlcyhds .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xefjlcyhds .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xefjlcyhds .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xefjlcyhds .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xefjlcyhds .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xefjlcyhds .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xefjlcyhds .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xefjlcyhds .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xefjlcyhds .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xefjlcyhds .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xefjlcyhds .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xefjlcyhds .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xefjlcyhds .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xefjlcyhds .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xefjlcyhds .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xefjlcyhds .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xefjlcyhds .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xefjlcyhds .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xefjlcyhds .gt_left {\n  text-align: left;\n}\n\n#xefjlcyhds .gt_center {\n  text-align: center;\n}\n\n#xefjlcyhds .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xefjlcyhds .gt_font_normal {\n  font-weight: normal;\n}\n\n#xefjlcyhds .gt_font_bold {\n  font-weight: bold;\n}\n\n#xefjlcyhds .gt_font_italic {\n  font-style: italic;\n}\n\n#xefjlcyhds .gt_super {\n  font-size: 65%;\n}\n\n#xefjlcyhds .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xefjlcyhds .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xefjlcyhds .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xefjlcyhds .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xefjlcyhds .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xefjlcyhds .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xefjlcyhds .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xefjlcyhds .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xefjlcyhds div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" style=\"table-layout:fixed;width:0px;\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <colgroup>\n    <col style=\"width:150px;\"/>\n    <col style=\"width:150px;\"/>\n    <col style=\"width:150px;\"/>\n    <col style=\"width:150px;\"/>\n    <col style=\"width:150px;\"/>\n    <col style=\"width:150px;\"/>\n    <col style=\"width:150px;\"/>\n    <col style=\"width:150px;\"/>\n    <col style=\"width:150px;\"/>\n  </colgroup>\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Obs\">Obs</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"A1\">A1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"A2\">A2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"A3\">A3</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"A4\">A4</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"A5\">A5</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"A6\">A6</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"A7\">A7</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"A8\">A8</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Obs\" class=\"gt_row gt_left\"></td>\n<td headers=\"A1\" class=\"gt_row gt_right\">19</td>\n<td headers=\"A2\" class=\"gt_row gt_right\">29</td>\n<td headers=\"A3\" class=\"gt_row gt_right\">10</td>\n<td headers=\"A4\" class=\"gt_row gt_right\">19</td>\n<td headers=\"A5\" class=\"gt_row gt_right\">42</td>\n<td headers=\"A6\" class=\"gt_row gt_right\">29</td>\n<td headers=\"A7\" class=\"gt_row gt_right\">28</td>\n<td headers=\"A8\" class=\"gt_row gt_right\">43</td></tr>\n    <tr><td headers=\"Obs\" class=\"gt_row gt_left\"></td>\n<td headers=\"A1\" class=\"gt_row gt_right\">29</td>\n<td headers=\"A2\" class=\"gt_row gt_right\">43</td>\n<td headers=\"A3\" class=\"gt_row gt_right\">14</td>\n<td headers=\"A4\" class=\"gt_row gt_right\">41</td>\n<td headers=\"A5\" class=\"gt_row gt_right\">29</td>\n<td headers=\"A6\" class=\"gt_row gt_right\">10</td>\n<td headers=\"A7\" class=\"gt_row gt_right\">42</td>\n<td headers=\"A8\" class=\"gt_row gt_right\">28</td></tr>\n    <tr><td headers=\"Obs\" class=\"gt_row gt_left\"></td>\n<td headers=\"A1\" class=\"gt_row gt_right\">10</td>\n<td headers=\"A2\" class=\"gt_row gt_right\">28</td>\n<td headers=\"A3\" class=\"gt_row gt_right\">42</td>\n<td headers=\"A4\" class=\"gt_row gt_right\">43</td>\n<td headers=\"A5\" class=\"gt_row gt_right\">41</td>\n<td headers=\"A6\" class=\"gt_row gt_right\">27</td>\n<td headers=\"A7\" class=\"gt_row gt_right\">10</td>\n<td headers=\"A8\" class=\"gt_row gt_right\">42</td></tr>\n    <tr><td headers=\"Obs\" class=\"gt_row gt_left\"></td>\n<td headers=\"A1\" class=\"gt_row gt_right\">42</td>\n<td headers=\"A2\" class=\"gt_row gt_right\">3</td>\n<td headers=\"A3\" class=\"gt_row gt_right\">28</td>\n<td headers=\"A4\" class=\"gt_row gt_right\">28</td>\n<td headers=\"A5\" class=\"gt_row gt_right\">14</td>\n<td headers=\"A6\" class=\"gt_row gt_right\">42</td>\n<td headers=\"A7\" class=\"gt_row gt_right\">43</td>\n<td headers=\"A8\" class=\"gt_row gt_right\">27</td></tr>\n    <tr><td headers=\"Obs\" class=\"gt_row gt_left\"></td>\n<td headers=\"A1\" class=\"gt_row gt_right\">43</td>\n<td headers=\"A2\" class=\"gt_row gt_right\">27</td>\n<td headers=\"A3\" class=\"gt_row gt_right\">29</td>\n<td headers=\"A4\" class=\"gt_row gt_right\">3</td>\n<td headers=\"A5\" class=\"gt_row gt_right\">28</td>\n<td headers=\"A6\" class=\"gt_row gt_right\">43</td>\n<td headers=\"A7\" class=\"gt_row gt_right\">27</td>\n<td headers=\"A8\" class=\"gt_row gt_right\">19</td></tr>\n    <tr><td headers=\"Obs\" class=\"gt_row gt_left\" style=\"background-color: #ADD8E6;\">Médias</td>\n<td headers=\"A1\" class=\"gt_row gt_right\" style=\"background-color: #ADD8E6;\">28.6</td>\n<td headers=\"A2\" class=\"gt_row gt_right\" style=\"background-color: #ADD8E6;\">26</td>\n<td headers=\"A3\" class=\"gt_row gt_right\" style=\"background-color: #ADD8E6;\">24.6</td>\n<td headers=\"A4\" class=\"gt_row gt_right\" style=\"background-color: #ADD8E6;\">26.8</td>\n<td headers=\"A5\" class=\"gt_row gt_right\" style=\"background-color: #ADD8E6;\">30.8</td>\n<td headers=\"A6\" class=\"gt_row gt_right\" style=\"background-color: #ADD8E6;\">30.2</td>\n<td headers=\"A7\" class=\"gt_row gt_right\" style=\"background-color: #ADD8E6;\">30</td>\n<td headers=\"A8\" class=\"gt_row gt_right\" style=\"background-color: #ADD8E6;\">31.8</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nCada coluna desta matriz corresponde a uma possível amostra aleatória e suas respectivas médias.\n\nAlgumas amostras tiveram médias muito distantes de $\\mu$, como: $\\overline{X_{A8}} = 31.8$ ou $\\overline{X_{A3}} = 24.6$. Esta variação é natural do processo amostral. Os métodos de amostragem e de inferência estatística tratam justamente de como interpretar e como lidar com esta variação. Para entender melhor este processo, vamos obter **todas** as 252 combinações possíveis de amostras com $n = 5$ e, em seguida, extrair suas respectivas médias. \n\nOs resultados das 252 médias possíveis podem ser vistos a seguir ordenados da menor para a maior média possível:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nAllcomb = combn(x = pop, m = 5)\nM_Allcomb = apply(Allcomb,2,mean)\nM_Allcomb_round = round(M_Allcomb,1)\nknitr::kable(matrix(M_Allcomb_round,nc = 14, byrow = T))\n```\n\n::: {.cell-output-display}\n\n\n|     |     |     |     |     |     |     |     |     |     |     |     |     |     |\n|----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|\n| 14.6| 14.8| 15.0| 17.4| 17.6| 17.8| 16.4| 16.6| 19.0| 19.2| 19.4| 16.8| 19.2| 19.4|\n| 19.6| 19.4| 19.6| 19.8| 22.0| 22.2| 22.4| 17.4| 17.6| 20.0| 20.2| 20.4| 17.8| 20.2|\n| 20.4| 20.6| 20.4| 20.6| 20.8| 23.0| 23.2| 23.4| 19.4| 21.8| 22.0| 22.2| 22.0| 22.2|\n| 22.4| 24.6| 24.8| 25.0| 22.2| 22.4| 22.6| 24.8| 25.0| 25.2| 25.0| 25.2| 25.4| 27.8|\n| 18.2| 18.4| 20.8| 21.0| 21.2| 18.6| 21.0| 21.2| 21.4| 21.2| 21.4| 21.6| 23.8| 24.0|\n| 24.2| 20.2| 22.6| 22.8| 23.0| 22.8| 23.0| 23.2| 25.4| 25.6| 25.8| 23.0| 23.2| 23.4|\n| 25.6| 25.8| 26.0| 25.8| 26.0| 26.2| 28.6| 21.2| 23.6| 23.8| 24.0| 23.8| 24.0| 24.2|\n| 26.4| 26.6| 26.8| 24.0| 24.2| 24.4| 26.6| 26.8| 27.0| 26.8| 27.0| 27.2| 29.6| 25.6|\n| 25.8| 26.0| 28.2| 28.4| 28.6| 28.4| 28.6| 28.8| 31.2| 28.6| 28.8| 29.0| 31.4| 31.6|\n| 19.6| 19.8| 22.2| 22.4| 22.6| 20.0| 22.4| 22.6| 22.8| 22.6| 22.8| 23.0| 25.2| 25.4|\n| 25.6| 21.6| 24.0| 24.2| 24.4| 24.2| 24.4| 24.6| 26.8| 27.0| 27.2| 24.4| 24.6| 24.8|\n| 27.0| 27.2| 27.4| 27.2| 27.4| 27.6| 30.0| 22.6| 25.0| 25.2| 25.4| 25.2| 25.4| 25.6|\n| 27.8| 28.0| 28.2| 25.4| 25.6| 25.8| 28.0| 28.2| 28.4| 28.2| 28.4| 28.6| 31.0| 27.0|\n| 27.2| 27.4| 29.6| 29.8| 30.0| 29.8| 30.0| 30.2| 32.6| 30.0| 30.2| 30.4| 32.8| 33.0|\n| 23.4| 25.8| 26.0| 26.2| 26.0| 26.2| 26.4| 28.6| 28.8| 29.0| 26.2| 26.4| 26.6| 28.8|\n| 29.0| 29.2| 29.0| 29.2| 29.4| 31.8| 27.8| 28.0| 28.2| 30.4| 30.6| 30.8| 30.6| 30.8|\n| 31.0| 33.4| 30.8| 31.0| 31.2| 33.6| 33.8| 28.8| 29.0| 29.2| 31.4| 31.6| 31.8| 31.6|\n| 31.8| 32.0| 34.4| 31.8| 32.0| 32.2| 34.6| 34.8| 33.4| 33.6| 33.8| 36.2| 36.4| 36.6|\n\n\n:::\n:::\n\n\n\n\nA menor e maior médias possíveis são 14.6 e 36.6 respectivamente. Estes valores são os mais distantes do parâmetro populacional ($\\mu = 25.6$) e ocorrem **puramente ao acaso** quanto são amostrados os 5 menores (3, 10, 14, 19, 27) ou os 5 maiores (43, 42, 41, 29, 28) elementos da população estatística. Estes casos extremos são **raros**. Em nosso exemplo, valores superiores a 33.8 ou inferiores a 17.4 são muito improváveis.\n\n\nPodemos avaliar graficamente a distribuição das médias amostrais através de um histograma. A grande maioria das médias amostrais concentra-se na porção intermediária do gráfico entre estes limites. Por exemplo, somente 3.2% das observações estão acima de 33.8. Da mesma forma, somente 3.2% das observações estão abaixo de 17.4\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nM_Allcomb_df = data.frame(M = as.numeric(M_Allcomb))\n\ngp5 <- ggplot(M_Allcomb_df, aes(x = M)) +\n  geom_histogram(fill = 'brown3', color = 'black', bins = 10) +\n  scale_x_continuous(breaks = seq(0, 50, by = 5)) +\n  coord_cartesian(xlim = c(10, 40)) +\n  labs(x = \"Médias\",\n       y = \"Frequência\") +\n  theme_classic()\n\ngp5\n```\n\n::: {.cell-output-display}\n![Histograma das 252 médias amostrais obtidas a partis de amostras de tamanho n = 5.](tipos-amostragem_files/figure-html/fig-hist-medias252-1.png){#fig-hist-medias252 width=672}\n:::\n:::\n\n\n\n\nSe calcularmos a **média das médias** ($\\mu_{\\overline{X}}$), ou seja, somarmos todos estes valores e dividirmos por 252, o resultado será 25.6, que é exatamente o valor da média populacional $\\mu$. Isto têm uma implicação  central em inferência estatística. Significa que a média amostral $\\overline{X}$ é um estimador **acurado** (= **não-viciado**), pois tende a estimar corretamente o valor da média populacional $\\mu$. Ou seja, o histograma acima está centrado ao redor de $\\mu$, o que significa que **em média** uma amostra particular tem maior probabilidade de expressar um $\\overline{X}$ próximo ao valor populacional. \n\n### Precisão: o erro padrão da média ($\\sigma_{\\overline{X}}$)\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nn2 = 7\nAllcomb7 = combn(x = pop, m = n2)\nM_Allcomb7 = apply(Allcomb7,2,mean)\nM_Allcomb7_round = round(M_Allcomb7,1)\nCT2 = choose(N,n2)\n```\n:::\n\n\n\n\nSuponha agora que tomemos ao acaso amostras com $n = 7$ desta mesma população. Existem ao todo:\n\n$${{10}\\choose{7}} = \\frac{10!}{(10-7)! \\times 7!} = 120$$\n\namostras diferentes de tamanho $n = 7$ que podem ser retiradas de uma população de tamanho  $n = 10$. Se tomarmos estas 120 amostras e calcularmos suas respectivas médias amostrais, teremos os resultados abaixo:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nknitr::kable(matrix(M_Allcomb7_round,nc = 12, byrow = T))\n```\n\n::: {.cell-output-display}\n\n\n|     |     |     |     |     |     |     |     |     |     |     |     |\n|----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|----:|\n| 18.6| 20.3| 20.4| 20.6| 20.4| 20.6| 20.7| 22.3| 22.4| 22.6| 20.6| 20.7|\n| 20.9| 22.4| 22.6| 22.7| 22.6| 22.7| 22.9| 24.6| 21.7| 21.9| 22.0| 23.6|\n| 23.7| 23.9| 23.7| 23.9| 24.0| 25.7| 23.9| 24.0| 24.1| 25.9| 26.0| 22.4|\n| 22.6| 22.7| 24.3| 24.4| 24.6| 24.4| 24.6| 24.7| 26.4| 24.6| 24.7| 24.9|\n| 26.6| 26.7| 25.7| 25.9| 26.0| 27.7| 27.9| 28.0| 23.0| 23.1| 23.3| 24.9|\n| 25.0| 25.1| 25.0| 25.1| 25.3| 27.0| 25.1| 25.3| 25.4| 27.1| 27.3| 26.3|\n| 26.4| 26.6| 28.3| 28.4| 28.6| 27.0| 27.1| 27.3| 29.0| 29.1| 29.3| 30.4|\n| 24.0| 24.1| 24.3| 25.9| 26.0| 26.1| 26.0| 26.1| 26.3| 28.0| 26.1| 26.3|\n| 26.4| 28.1| 28.3| 27.3| 27.4| 27.6| 29.3| 29.4| 29.6| 28.0| 28.1| 28.3|\n| 30.0| 30.1| 30.3| 31.4| 28.6| 28.7| 28.9| 30.6| 30.7| 30.9| 32.0| 32.7|\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nM_Allcomb7_df = data.frame(M = as.numeric(M_Allcomb7))\n\ngp7 <- ggplot(M_Allcomb7_df, aes(x = M)) +\n  geom_histogram(fill = 'brown3', color = 'black', bins = 10) +\n  scale_x_continuous(breaks = seq(0, 50, by = 5)) +\n  coord_cartesian(xlim = c(10, 40)) +\n  labs(x = \"Média\",\n       y = \"Frequência\") +\n  theme_classic()\n\ngp7\n```\n\n::: {.cell-output-display}\n![Histograma das 120 médias amostrais obtidas a partis de amostras de tamanho n = 7](tipos-amostragem_files/figure-html/fig-hist-medias120-1.png){#fig-hist-medias120 width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nmu_pop = mean(pop)\nN = length(pop)\nvar_pop = mean((pop - mu_pop)^2)\nsigma_pop = sqrt(var_pop)\n\nep5 = sigma_pop/sqrt(n)\nep7 = sigma_pop/sqrt(n2)\n```\n:::\n\n\n\n\nSe compararmos os histogramas com $n = 5$ e $n = 7$ (@fig-hist-medias252 e @fig-hist-medias120), veremos que os dois resultam em estimadores acurados, pois $\\mu_{\\overline{X}} = \\mu$. No entando, o **intervalo de variação** é menor para amostras de tamanho $n = 7$. Para esta figura, os valores estão mais concentrados ao redor da média. Portanto, à medida que aumenta o tamanho amostral, diminui a dispersão das médias amostrais ao redor de $\\mu$. Assim, para amostras grandes torna-se mais **improvável** obter uma média amostral distante da média populacional. Dizemos então que conforme aumenta o tamanho amostral, conseguimos estimativas mais precisas.\n\n\nA precisão de um estimador pode ser medida pelo **Erro padrão da média** ($\\sigma_{\\overline{X}}$) que pode ser calculado por:\n\n$$\\sigma_{\\overline{X}} = \\frac{\\sigma}{\\sqrt{n}}$$\n\nO erro padrão da média é o desvio padrão de **todas** as médias amostrais que poderiam ser obtidas de uma amostra com tamanho $n$. Para nosso exemplo com $n = 5$, $\\sigma_{\\overline{X}}$ = 5.93, enquanto para $n = 7$, $\\sigma_{\\overline{X}}$ = 5.01. Dizemos que o último exemplo fornece estimativas **mais precisas**. \n\n:::{.callout-note}\n\n# Erro padrão amostral\n\nNa prática científica não conhecemos o desvio padrão populacional $\\sigma$ e, consequentemente, não temos obter o erro padrão populacional $\\sigma_{\\overline{X}}$. No entanto, dado que temos uma amostra particular, podemos **estimá-lo** a partir do desvio padrão amostral $\\sigma_{\\overline{X}}$ pela expressão:\n\n$$s_{\\overline{X}} = \\frac{s}{\\sqrt{n}}$$\n\nem que $s_{\\overline{X}}$ é denominado de **erro padrão amostral**\n\n:::\n\n___\n\n:::{.callout-note}\n# Vídeo-aulas\n\n<iframe\n  style=\"width:100%; aspect-ratio:16/9;\"\n  src=\"https://www.youtube-nocookie.com/embed/iyzCGvlxN-o\"\n  title=\"YouTube video player\"\n  frameborder=\"0\"\n  allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share\"\n  allowfullscreen>\n</iframe>\n\n:::",
    "supporting": [
      "tipos-amostragem_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}