{
  "hash": "5094bf56a9819375ee111106c7fa3acc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Descrevendo variáveis quantitativas\"\ndescription: \"Exploração de variáveis quantitativas por meio de tabelas de frequência, histogramas e gráficos de frequência acumulada.\"\ncategories: [\n          \"R\",\n          \"Ciência de dados\",\n          \"Análise de dados\",\n          \"Estatística descritiva\",\n          \"Variáveis quantitativas\",\n          \"Distribuição de frequência\"\n        ]\n\nimage: \"images/varquanti.jpg\"\nexecute:\n  echo: true\n  warning: false\n  include: true\n  message: false\nformat:\n  html:\n    code-fold: false\n---\n\n\n\n\n:::{.callout-tip collapse=\"true\"}\n## Pacotes e funções utilizados\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gt)\n```\n:::\n\n\n\n:::\n\nVariáveis quantitativas podem ser discretas ou contínuas. A descrição dos padrões de distribuição para esses tipos de variáveis é feita utilizando tabelas (frequência e frequência acumulada) e gráficos (histogramas ou gráficos de frequência acumulada).\n\n## Tabelas de frequência para variáveis quantitativas\n\nA construção de tabelas de frequências para variáveis quantitativas necessita que agrupemos as observações em *faixas de valores*. Veja as observações abaixo por exemplo:\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n$X =$ \\{2.66, 3.72, 5.73, 9.08, 2.02, 8.98, 9.45, 6.61, 6.29, 0.62\\}\n\nPodemos agrupá-las nas seguintes faixas de valores:\n\n(0,2], (2,4], (4,6], (6,8], (8,10]\n\nEstas faixas de valores são denominadas de **intervalos de classe**. Se alocadas nestes intervalos, as observações ficam:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nX <- c(2.66, 3.72, 5.73, 9.08, 2.02, 8.98, 9.45, 6.61, 6.29, 0.62)\nClasses <- cut(X, seq(0, 10, by = 2))\n\ndf <- data.frame(X, Classes)\n\ndf |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"sauujvnjgi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#sauujvnjgi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#sauujvnjgi thead, #sauujvnjgi tbody, #sauujvnjgi tfoot, #sauujvnjgi tr, #sauujvnjgi td, #sauujvnjgi th {\n  border-style: none;\n}\n\n#sauujvnjgi p {\n  margin: 0;\n  padding: 0;\n}\n\n#sauujvnjgi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#sauujvnjgi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#sauujvnjgi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#sauujvnjgi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#sauujvnjgi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sauujvnjgi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sauujvnjgi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sauujvnjgi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#sauujvnjgi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#sauujvnjgi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#sauujvnjgi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#sauujvnjgi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#sauujvnjgi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#sauujvnjgi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#sauujvnjgi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#sauujvnjgi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#sauujvnjgi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#sauujvnjgi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#sauujvnjgi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sauujvnjgi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#sauujvnjgi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#sauujvnjgi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#sauujvnjgi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sauujvnjgi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#sauujvnjgi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#sauujvnjgi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sauujvnjgi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sauujvnjgi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#sauujvnjgi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sauujvnjgi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#sauujvnjgi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sauujvnjgi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sauujvnjgi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sauujvnjgi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sauujvnjgi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sauujvnjgi .gt_left {\n  text-align: left;\n}\n\n#sauujvnjgi .gt_center {\n  text-align: center;\n}\n\n#sauujvnjgi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#sauujvnjgi .gt_font_normal {\n  font-weight: normal;\n}\n\n#sauujvnjgi .gt_font_bold {\n  font-weight: bold;\n}\n\n#sauujvnjgi .gt_font_italic {\n  font-style: italic;\n}\n\n#sauujvnjgi .gt_super {\n  font-size: 65%;\n}\n\n#sauujvnjgi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#sauujvnjgi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#sauujvnjgi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#sauujvnjgi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#sauujvnjgi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#sauujvnjgi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#sauujvnjgi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#sauujvnjgi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#sauujvnjgi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"X\">X</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Classes\">Classes</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"X\" class=\"gt_row gt_right\">2.66</td>\n<td headers=\"Classes\" class=\"gt_row gt_center\">(2,4]</td></tr>\n    <tr><td headers=\"X\" class=\"gt_row gt_right\">3.72</td>\n<td headers=\"Classes\" class=\"gt_row gt_center\">(2,4]</td></tr>\n    <tr><td headers=\"X\" class=\"gt_row gt_right\">5.73</td>\n<td headers=\"Classes\" class=\"gt_row gt_center\">(4,6]</td></tr>\n    <tr><td headers=\"X\" class=\"gt_row gt_right\">9.08</td>\n<td headers=\"Classes\" class=\"gt_row gt_center\">(8,10]</td></tr>\n    <tr><td headers=\"X\" class=\"gt_row gt_right\">2.02</td>\n<td headers=\"Classes\" class=\"gt_row gt_center\">(2,4]</td></tr>\n    <tr><td headers=\"X\" class=\"gt_row gt_right\">8.98</td>\n<td headers=\"Classes\" class=\"gt_row gt_center\">(8,10]</td></tr>\n    <tr><td headers=\"X\" class=\"gt_row gt_right\">9.45</td>\n<td headers=\"Classes\" class=\"gt_row gt_center\">(8,10]</td></tr>\n    <tr><td headers=\"X\" class=\"gt_row gt_right\">6.61</td>\n<td headers=\"Classes\" class=\"gt_row gt_center\">(6,8]</td></tr>\n    <tr><td headers=\"X\" class=\"gt_row gt_right\">6.29</td>\n<td headers=\"Classes\" class=\"gt_row gt_center\">(6,8]</td></tr>\n    <tr><td headers=\"X\" class=\"gt_row gt_right\">0.62</td>\n<td headers=\"Classes\" class=\"gt_row gt_center\">(0,2]</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nUma tabela de frequência para estas observações é construída contando o número de observações por intervalo de classes. Neste caso:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf |> \n  group_by(Classes) |> \n  summarise(Frequencia = n()) |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"oueiyneebj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#oueiyneebj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#oueiyneebj thead, #oueiyneebj tbody, #oueiyneebj tfoot, #oueiyneebj tr, #oueiyneebj td, #oueiyneebj th {\n  border-style: none;\n}\n\n#oueiyneebj p {\n  margin: 0;\n  padding: 0;\n}\n\n#oueiyneebj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#oueiyneebj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#oueiyneebj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#oueiyneebj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#oueiyneebj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oueiyneebj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oueiyneebj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#oueiyneebj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#oueiyneebj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#oueiyneebj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#oueiyneebj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#oueiyneebj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#oueiyneebj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#oueiyneebj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#oueiyneebj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#oueiyneebj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#oueiyneebj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#oueiyneebj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#oueiyneebj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oueiyneebj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#oueiyneebj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#oueiyneebj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#oueiyneebj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oueiyneebj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#oueiyneebj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#oueiyneebj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oueiyneebj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oueiyneebj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#oueiyneebj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oueiyneebj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#oueiyneebj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#oueiyneebj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oueiyneebj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oueiyneebj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#oueiyneebj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#oueiyneebj .gt_left {\n  text-align: left;\n}\n\n#oueiyneebj .gt_center {\n  text-align: center;\n}\n\n#oueiyneebj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#oueiyneebj .gt_font_normal {\n  font-weight: normal;\n}\n\n#oueiyneebj .gt_font_bold {\n  font-weight: bold;\n}\n\n#oueiyneebj .gt_font_italic {\n  font-style: italic;\n}\n\n#oueiyneebj .gt_super {\n  font-size: 65%;\n}\n\n#oueiyneebj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#oueiyneebj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#oueiyneebj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#oueiyneebj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#oueiyneebj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#oueiyneebj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#oueiyneebj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#oueiyneebj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#oueiyneebj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Classes\">Classes</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Frequencia\">Frequencia</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(0,2]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(2,4]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(4,6]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(6,8]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(8,10]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">3</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nNa coluna `Frequencia`, temos o número de observações da variável `X` para cada um dos intervalos de classe.\n\n### Alterando o tamanho dos intervalos de classe\n\nNo exemplo anterior, definimos os limites dos intervalos de classe de 2 em 2 unidades. Poderíamos ter escolhido outros tamanhos, por exemplo, de 4 em 4. Neste caso teríamos:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nClasses <- cut(X, seq(0, 12, by = 4))\ndata.frame(X, Classes) |> \n  group_by(Classes) |> \n  summarise(Frequencia = n()) |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yloatcfjjf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yloatcfjjf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yloatcfjjf thead, #yloatcfjjf tbody, #yloatcfjjf tfoot, #yloatcfjjf tr, #yloatcfjjf td, #yloatcfjjf th {\n  border-style: none;\n}\n\n#yloatcfjjf p {\n  margin: 0;\n  padding: 0;\n}\n\n#yloatcfjjf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yloatcfjjf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yloatcfjjf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yloatcfjjf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yloatcfjjf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yloatcfjjf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yloatcfjjf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yloatcfjjf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yloatcfjjf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yloatcfjjf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yloatcfjjf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yloatcfjjf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yloatcfjjf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yloatcfjjf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yloatcfjjf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yloatcfjjf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yloatcfjjf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yloatcfjjf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yloatcfjjf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yloatcfjjf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yloatcfjjf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yloatcfjjf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yloatcfjjf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yloatcfjjf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yloatcfjjf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yloatcfjjf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yloatcfjjf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yloatcfjjf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yloatcfjjf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yloatcfjjf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yloatcfjjf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yloatcfjjf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yloatcfjjf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yloatcfjjf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yloatcfjjf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yloatcfjjf .gt_left {\n  text-align: left;\n}\n\n#yloatcfjjf .gt_center {\n  text-align: center;\n}\n\n#yloatcfjjf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yloatcfjjf .gt_font_normal {\n  font-weight: normal;\n}\n\n#yloatcfjjf .gt_font_bold {\n  font-weight: bold;\n}\n\n#yloatcfjjf .gt_font_italic {\n  font-style: italic;\n}\n\n#yloatcfjjf .gt_super {\n  font-size: 65%;\n}\n\n#yloatcfjjf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yloatcfjjf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yloatcfjjf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yloatcfjjf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yloatcfjjf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yloatcfjjf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yloatcfjjf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yloatcfjjf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yloatcfjjf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Classes\">Classes</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Frequencia\">Frequencia</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(0,4]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(4,8]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(8,12]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">3</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nNote que ao escolhermos o tamanho dos intervalos de classe, estamos criando a variável qualitativa ordinal `Classes`, a partir do agrupamento das observações em `X`. Neste sentido, não há um único tamanho *correto* para os intervalos de classe. O objetivo é encontrar um tamanho que permita evidenciar os padrões de distribuição da variável sem perdermos muitos detalhes.\n\nPoderíamos escolher um tamanho muito grande, de 5 em 5. Neste caso, teríamos somente 2 grupos.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nClasses <- cut(X, seq(0, 10, by = 5))\ndata.frame(X, Classes) |> \n  group_by(Classes) |> \n  summarise(Frequencia = n()) |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"ottzlywfyh\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ottzlywfyh table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ottzlywfyh thead, #ottzlywfyh tbody, #ottzlywfyh tfoot, #ottzlywfyh tr, #ottzlywfyh td, #ottzlywfyh th {\n  border-style: none;\n}\n\n#ottzlywfyh p {\n  margin: 0;\n  padding: 0;\n}\n\n#ottzlywfyh .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ottzlywfyh .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ottzlywfyh .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ottzlywfyh .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ottzlywfyh .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ottzlywfyh .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ottzlywfyh .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ottzlywfyh .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ottzlywfyh .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ottzlywfyh .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ottzlywfyh .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ottzlywfyh .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ottzlywfyh .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ottzlywfyh .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ottzlywfyh .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ottzlywfyh .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ottzlywfyh .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ottzlywfyh .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ottzlywfyh .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ottzlywfyh .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ottzlywfyh .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ottzlywfyh .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ottzlywfyh .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ottzlywfyh .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ottzlywfyh .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ottzlywfyh .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ottzlywfyh .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ottzlywfyh .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ottzlywfyh .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ottzlywfyh .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ottzlywfyh .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ottzlywfyh .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ottzlywfyh .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ottzlywfyh .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ottzlywfyh .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ottzlywfyh .gt_left {\n  text-align: left;\n}\n\n#ottzlywfyh .gt_center {\n  text-align: center;\n}\n\n#ottzlywfyh .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ottzlywfyh .gt_font_normal {\n  font-weight: normal;\n}\n\n#ottzlywfyh .gt_font_bold {\n  font-weight: bold;\n}\n\n#ottzlywfyh .gt_font_italic {\n  font-style: italic;\n}\n\n#ottzlywfyh .gt_super {\n  font-size: 65%;\n}\n\n#ottzlywfyh .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ottzlywfyh .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ottzlywfyh .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ottzlywfyh .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ottzlywfyh .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ottzlywfyh .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ottzlywfyh .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#ottzlywfyh .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#ottzlywfyh div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Classes\">Classes</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Frequencia\">Frequencia</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(0,5]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(5,10]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">6</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nPor outro lado, poderíamos escolher um tamanho muito pequeno, por exemplo, de 1 em 1.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nClasses <- cut(X, seq(0, 10, by = 1))\ndata.frame(X, Classes) |> \n  group_by(Classes) |> \n  summarise(Frequencia = n()) |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"lywxfzgsjf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#lywxfzgsjf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#lywxfzgsjf thead, #lywxfzgsjf tbody, #lywxfzgsjf tfoot, #lywxfzgsjf tr, #lywxfzgsjf td, #lywxfzgsjf th {\n  border-style: none;\n}\n\n#lywxfzgsjf p {\n  margin: 0;\n  padding: 0;\n}\n\n#lywxfzgsjf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#lywxfzgsjf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#lywxfzgsjf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#lywxfzgsjf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#lywxfzgsjf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lywxfzgsjf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lywxfzgsjf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#lywxfzgsjf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#lywxfzgsjf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#lywxfzgsjf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#lywxfzgsjf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#lywxfzgsjf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#lywxfzgsjf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#lywxfzgsjf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#lywxfzgsjf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#lywxfzgsjf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#lywxfzgsjf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#lywxfzgsjf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#lywxfzgsjf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lywxfzgsjf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#lywxfzgsjf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#lywxfzgsjf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#lywxfzgsjf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lywxfzgsjf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#lywxfzgsjf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#lywxfzgsjf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lywxfzgsjf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lywxfzgsjf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#lywxfzgsjf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lywxfzgsjf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#lywxfzgsjf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#lywxfzgsjf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lywxfzgsjf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lywxfzgsjf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#lywxfzgsjf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#lywxfzgsjf .gt_left {\n  text-align: left;\n}\n\n#lywxfzgsjf .gt_center {\n  text-align: center;\n}\n\n#lywxfzgsjf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#lywxfzgsjf .gt_font_normal {\n  font-weight: normal;\n}\n\n#lywxfzgsjf .gt_font_bold {\n  font-weight: bold;\n}\n\n#lywxfzgsjf .gt_font_italic {\n  font-style: italic;\n}\n\n#lywxfzgsjf .gt_super {\n  font-size: 65%;\n}\n\n#lywxfzgsjf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#lywxfzgsjf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#lywxfzgsjf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#lywxfzgsjf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#lywxfzgsjf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#lywxfzgsjf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#lywxfzgsjf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#lywxfzgsjf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#lywxfzgsjf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Classes\">Classes</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Frequencia\">Frequencia</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(0,1]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(2,3]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(3,4]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(5,6]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(6,7]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">2</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(8,9]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"Classes\" class=\"gt_row gt_center\">(9,10]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">2</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nNas duas situações, não é possível evidenciar os padrões de distribuição da variável `X`. Na primeira, perdemos muita informação agrupando as observações em somente duas faixas e, na última, perdemos a capacidade de visualizar os padrões de distribuição de `X`.\n\n### Tabela de frequência para a `CPUE`\n\nImporte a base de dados `Reservatorios_Parana_parcial.csv`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres <- read_delim(\n  file = \"https://raw.githubusercontent.com/FCopf/datasets/refs/heads/main/Reservatorios_Parana_parcial.csv\",\n  delim = \",\",\n  locale = locale(decimal_mark = \".\", encoding = \"latin1\")\n)\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nNo objeto `res`, temos 8 variáveis quantitativas: Fechamento, Area, pH, Condutividade, Alcalinidade, P.total, Riqueza, CPUE. Vamos verificar como fica uma tabela de frequências para a variável `CPUE`, que expressa a captura em $kg$ de peixes em cada reservatório. Inicialmente, vamos selecionar somente esta coluna da tabela e visualizá-la em ordem crescente.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsort(res$CPUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  2.05  2.43  4.01  4.71  5.60  5.95  6.29  7.35  7.51  7.75  7.95  9.22\n[13]  9.40 11.59 11.73 11.74 12.55 13.04 13.12 13.67 13.72 13.86 16.10 16.50\n[25] 17.95 20.83 20.92 21.82 24.88 28.73 30.76\n```\n\n\n:::\n:::\n\n\n\n\nVemos que o menor valor é 2.05 $kg$ e o maior 30.76 $kg$. Assumindo que temos 31 observações, vamos criar um intervalo de classes de 5 em 5 unidades. Para isso, criaremos a variável `cl_cpue`, que será uma sequência de $0$ a $35$, com tamanho $5$. Os valores nesta sequência são os *limites de classe*.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncl_cpue <- seq(from = 0, to = 35, by = 5)\ncl_cpue\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1]  0  5 10 15 20 25 30 35\n```\n\n\n:::\n:::\n\n\n\n\nUtilizaremos os limites de classe para gerar uma nova coluna, delimitando os intervalos a que cada observação pertence. Para isso, utilizaremos a função `cut`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_cpue <- res |> \n  select(CPUE) |> \n  mutate(int_cpue = cut(CPUE, breaks = cl_cpue))\n```\n:::\n\n\n\n\nE veremos a tabela em ordem crescente de classes para facilitar a identificação de padrões.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntab_cpue |> \n  arrange(CPUE) |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"xnbmrvnfas\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xnbmrvnfas table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xnbmrvnfas thead, #xnbmrvnfas tbody, #xnbmrvnfas tfoot, #xnbmrvnfas tr, #xnbmrvnfas td, #xnbmrvnfas th {\n  border-style: none;\n}\n\n#xnbmrvnfas p {\n  margin: 0;\n  padding: 0;\n}\n\n#xnbmrvnfas .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xnbmrvnfas .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xnbmrvnfas .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xnbmrvnfas .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xnbmrvnfas .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xnbmrvnfas .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xnbmrvnfas .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xnbmrvnfas .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xnbmrvnfas .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xnbmrvnfas .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xnbmrvnfas .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xnbmrvnfas .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xnbmrvnfas .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xnbmrvnfas .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xnbmrvnfas .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xnbmrvnfas .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xnbmrvnfas .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xnbmrvnfas .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xnbmrvnfas .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnbmrvnfas .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xnbmrvnfas .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xnbmrvnfas .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xnbmrvnfas .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnbmrvnfas .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xnbmrvnfas .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xnbmrvnfas .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xnbmrvnfas .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnbmrvnfas .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xnbmrvnfas .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xnbmrvnfas .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xnbmrvnfas .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xnbmrvnfas .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xnbmrvnfas .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnbmrvnfas .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xnbmrvnfas .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xnbmrvnfas .gt_left {\n  text-align: left;\n}\n\n#xnbmrvnfas .gt_center {\n  text-align: center;\n}\n\n#xnbmrvnfas .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xnbmrvnfas .gt_font_normal {\n  font-weight: normal;\n}\n\n#xnbmrvnfas .gt_font_bold {\n  font-weight: bold;\n}\n\n#xnbmrvnfas .gt_font_italic {\n  font-style: italic;\n}\n\n#xnbmrvnfas .gt_super {\n  font-size: 65%;\n}\n\n#xnbmrvnfas .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xnbmrvnfas .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xnbmrvnfas .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xnbmrvnfas .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xnbmrvnfas .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xnbmrvnfas .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xnbmrvnfas .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#xnbmrvnfas .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#xnbmrvnfas div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CPUE\">CPUE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"int_cpue\">int_cpue</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">2.05</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(0,5]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">2.43</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(0,5]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">4.01</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(0,5]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">4.71</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(0,5]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">5.60</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(5,10]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">5.95</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(5,10]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">6.29</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(5,10]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">7.35</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(5,10]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">7.51</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(5,10]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">7.75</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(5,10]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">7.95</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(5,10]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">9.22</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(5,10]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">9.40</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(5,10]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">11.59</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(10,15]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">11.73</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(10,15]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">11.74</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(10,15]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">12.55</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(10,15]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">13.04</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(10,15]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">13.12</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(10,15]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">13.67</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(10,15]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">13.72</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(10,15]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">13.86</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(10,15]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">16.10</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(15,20]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">16.50</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(15,20]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">17.95</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(15,20]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">20.83</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(20,25]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">20.92</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(20,25]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">21.82</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(20,25]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">24.88</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(20,25]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">28.73</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(25,30]</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">30.76</td>\n<td headers=\"int_cpue\" class=\"gt_row gt_center\">(30,35]</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nA nova tabela `tab_cpue` tem agora duas colunas: os valores numéricos de `CPUE` e os valores transformados em intervalos de classe, `int_cpue`. É com esta última que montaremos a tabela de frequência.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfre_cpue <- tab_cpue |> \n  group_by(int_cpue) |> \n  summarise(Frequencia = n())\n\nfre_cpue |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"shfwlfhgkq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#shfwlfhgkq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#shfwlfhgkq thead, #shfwlfhgkq tbody, #shfwlfhgkq tfoot, #shfwlfhgkq tr, #shfwlfhgkq td, #shfwlfhgkq th {\n  border-style: none;\n}\n\n#shfwlfhgkq p {\n  margin: 0;\n  padding: 0;\n}\n\n#shfwlfhgkq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#shfwlfhgkq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#shfwlfhgkq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#shfwlfhgkq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#shfwlfhgkq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#shfwlfhgkq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shfwlfhgkq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#shfwlfhgkq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#shfwlfhgkq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#shfwlfhgkq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#shfwlfhgkq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#shfwlfhgkq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#shfwlfhgkq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#shfwlfhgkq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#shfwlfhgkq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#shfwlfhgkq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#shfwlfhgkq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#shfwlfhgkq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#shfwlfhgkq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shfwlfhgkq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#shfwlfhgkq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#shfwlfhgkq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#shfwlfhgkq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shfwlfhgkq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#shfwlfhgkq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#shfwlfhgkq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shfwlfhgkq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shfwlfhgkq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#shfwlfhgkq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shfwlfhgkq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#shfwlfhgkq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#shfwlfhgkq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#shfwlfhgkq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shfwlfhgkq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#shfwlfhgkq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#shfwlfhgkq .gt_left {\n  text-align: left;\n}\n\n#shfwlfhgkq .gt_center {\n  text-align: center;\n}\n\n#shfwlfhgkq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#shfwlfhgkq .gt_font_normal {\n  font-weight: normal;\n}\n\n#shfwlfhgkq .gt_font_bold {\n  font-weight: bold;\n}\n\n#shfwlfhgkq .gt_font_italic {\n  font-style: italic;\n}\n\n#shfwlfhgkq .gt_super {\n  font-size: 65%;\n}\n\n#shfwlfhgkq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#shfwlfhgkq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#shfwlfhgkq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#shfwlfhgkq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#shfwlfhgkq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#shfwlfhgkq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#shfwlfhgkq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#shfwlfhgkq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#shfwlfhgkq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"int_cpue\">int_cpue</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Frequencia\">Frequencia</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(0,5]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(5,10]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">9</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(10,15]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">9</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(15,20]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">3</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(20,25]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">4</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(25,30]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">1</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(30,35]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">1</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nE, em seguida, de frequência relativa:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfre_cpue <- fre_cpue |> \n  mutate(Freq_relativa = Frequencia / sum(Frequencia))\n\nfre_cpue |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"dmhypywntg\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#dmhypywntg table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#dmhypywntg thead, #dmhypywntg tbody, #dmhypywntg tfoot, #dmhypywntg tr, #dmhypywntg td, #dmhypywntg th {\n  border-style: none;\n}\n\n#dmhypywntg p {\n  margin: 0;\n  padding: 0;\n}\n\n#dmhypywntg .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#dmhypywntg .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#dmhypywntg .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#dmhypywntg .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#dmhypywntg .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dmhypywntg .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dmhypywntg .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#dmhypywntg .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#dmhypywntg .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#dmhypywntg .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#dmhypywntg .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#dmhypywntg .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#dmhypywntg .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#dmhypywntg .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#dmhypywntg .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#dmhypywntg .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#dmhypywntg .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#dmhypywntg .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#dmhypywntg .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmhypywntg .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#dmhypywntg .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#dmhypywntg .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#dmhypywntg .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmhypywntg .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#dmhypywntg .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#dmhypywntg .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dmhypywntg .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmhypywntg .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#dmhypywntg .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dmhypywntg .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#dmhypywntg .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#dmhypywntg .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dmhypywntg .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmhypywntg .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#dmhypywntg .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#dmhypywntg .gt_left {\n  text-align: left;\n}\n\n#dmhypywntg .gt_center {\n  text-align: center;\n}\n\n#dmhypywntg .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#dmhypywntg .gt_font_normal {\n  font-weight: normal;\n}\n\n#dmhypywntg .gt_font_bold {\n  font-weight: bold;\n}\n\n#dmhypywntg .gt_font_italic {\n  font-style: italic;\n}\n\n#dmhypywntg .gt_super {\n  font-size: 65%;\n}\n\n#dmhypywntg .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#dmhypywntg .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#dmhypywntg .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#dmhypywntg .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#dmhypywntg .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#dmhypywntg .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#dmhypywntg .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#dmhypywntg .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#dmhypywntg div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"int_cpue\">int_cpue</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Frequencia\">Frequencia</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Freq_relativa\">Freq_relativa</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(0,5]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">4</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.12903226</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(5,10]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">9</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.29032258</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(10,15]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">9</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.29032258</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(15,20]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">3</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.09677419</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(20,25]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">4</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.12903226</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(25,30]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.03225806</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(30,35]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.03225806</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nVeja que os intervalos de (5,10] e (10,15] contêm o maior número de observações, cerca de 29\\% cada um, e que acima de $25$ $kg$ temos somente duas observações.\n\n### Tabela de frequência acumulada\n\nOutra forma de representar o padrão de distribuição para uma variável quantitativa é apresentá-la em uma tabela de frequência acumulada. Fazemos isso somando de forma cumulativa as observações em cada classe de intervalo e criando duas colunas adicionais de frequência acumulada e de frequência relativa acumulada.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfre_cpue <- fre_cpue |> \n  mutate(F_acumulada = cumsum(Frequencia),\n         FR_acumulada = cumsum(Freq_relativa))\n\nfre_cpue |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"mvlpamufqi\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mvlpamufqi table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mvlpamufqi thead, #mvlpamufqi tbody, #mvlpamufqi tfoot, #mvlpamufqi tr, #mvlpamufqi td, #mvlpamufqi th {\n  border-style: none;\n}\n\n#mvlpamufqi p {\n  margin: 0;\n  padding: 0;\n}\n\n#mvlpamufqi .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mvlpamufqi .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mvlpamufqi .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mvlpamufqi .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mvlpamufqi .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mvlpamufqi .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mvlpamufqi .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mvlpamufqi .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mvlpamufqi .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mvlpamufqi .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mvlpamufqi .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mvlpamufqi .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mvlpamufqi .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mvlpamufqi .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mvlpamufqi .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mvlpamufqi .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mvlpamufqi .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mvlpamufqi .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mvlpamufqi .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mvlpamufqi .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mvlpamufqi .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mvlpamufqi .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mvlpamufqi .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mvlpamufqi .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mvlpamufqi .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mvlpamufqi .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mvlpamufqi .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mvlpamufqi .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mvlpamufqi .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mvlpamufqi .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mvlpamufqi .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mvlpamufqi .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mvlpamufqi .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mvlpamufqi .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mvlpamufqi .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mvlpamufqi .gt_left {\n  text-align: left;\n}\n\n#mvlpamufqi .gt_center {\n  text-align: center;\n}\n\n#mvlpamufqi .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mvlpamufqi .gt_font_normal {\n  font-weight: normal;\n}\n\n#mvlpamufqi .gt_font_bold {\n  font-weight: bold;\n}\n\n#mvlpamufqi .gt_font_italic {\n  font-style: italic;\n}\n\n#mvlpamufqi .gt_super {\n  font-size: 65%;\n}\n\n#mvlpamufqi .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mvlpamufqi .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mvlpamufqi .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mvlpamufqi .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mvlpamufqi .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mvlpamufqi .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mvlpamufqi .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#mvlpamufqi .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#mvlpamufqi div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"int_cpue\">int_cpue</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Frequencia\">Frequencia</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Freq_relativa\">Freq_relativa</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"F_acumulada\">F_acumulada</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"FR_acumulada\">FR_acumulada</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(0,5]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">4</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.12903226</td>\n<td headers=\"F_acumulada\" class=\"gt_row gt_right\">4</td>\n<td headers=\"FR_acumulada\" class=\"gt_row gt_right\">0.1290323</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(5,10]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">9</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.29032258</td>\n<td headers=\"F_acumulada\" class=\"gt_row gt_right\">13</td>\n<td headers=\"FR_acumulada\" class=\"gt_row gt_right\">0.4193548</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(10,15]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">9</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.29032258</td>\n<td headers=\"F_acumulada\" class=\"gt_row gt_right\">22</td>\n<td headers=\"FR_acumulada\" class=\"gt_row gt_right\">0.7096774</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(15,20]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">3</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.09677419</td>\n<td headers=\"F_acumulada\" class=\"gt_row gt_right\">25</td>\n<td headers=\"FR_acumulada\" class=\"gt_row gt_right\">0.8064516</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(20,25]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">4</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.12903226</td>\n<td headers=\"F_acumulada\" class=\"gt_row gt_right\">29</td>\n<td headers=\"FR_acumulada\" class=\"gt_row gt_right\">0.9354839</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(25,30]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.03225806</td>\n<td headers=\"F_acumulada\" class=\"gt_row gt_right\">30</td>\n<td headers=\"FR_acumulada\" class=\"gt_row gt_right\">0.9677419</td></tr>\n    <tr><td headers=\"int_cpue\" class=\"gt_row gt_center\">(30,35]</td>\n<td headers=\"Frequencia\" class=\"gt_row gt_right\">1</td>\n<td headers=\"Freq_relativa\" class=\"gt_row gt_right\">0.03225806</td>\n<td headers=\"F_acumulada\" class=\"gt_row gt_right\">31</td>\n<td headers=\"FR_acumulada\" class=\"gt_row gt_right\">1.0000000</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nVeja agora que a última linha da coluna de frequência acumulada é igual ao número de observações total e que a da frequência relativa acumulada é igual a 1.\n\n## Representação gráfica: histogramas\n\nHistogramas são representações das tabelas de frequência e de frequência relativa. Um histograma da coluna `CPUE` pode ser feito com o comando:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(res, aes(x = CPUE)) +\n  geom_histogram()\n```\n\n::: {.cell-output-display}\n![](varquant_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\n\n\nOs intervalos de classe foram escolhidos automaticamente pela função `geom_histogram`. Se quisermos ter o controle sobre estes intervalos, podemos adicionar o argumento `breaks` e a sequência com os limites de classe que criamos anteriormente:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(res, aes(x = CPUE)) +\n  geom_histogram(breaks = cl_cpue)\n```\n\n::: {.cell-output-display}\n![](varquant_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n\nA formatação do histograma acima pode ser melhorada de diversas formas, por exemplo:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(res, aes(x = CPUE, label = after_stat(count))) +\n  geom_histogram(breaks = cl_cpue, \n                 fill = 'darkblue', color = 'white') +\n  labs(x = 'Captura em kg', y = 'Frequência') +\n  geom_text(stat = \"bin\", size = 6, vjust = 1.5, color = 'white',\n            breaks = cl_cpue) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](varquant_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\n\n\n+ Modificamos a cor do preenchimento (`fill = 'darkblue'`), e identificamos as barras individualmente traçando uma linha branca entre elas (`color = 'white'`);\n+ Reescrevemos o rótulo dos eixos $x$ e $y$ (`labs()`);\n+ Identificamos as frequências em cada barra individualmente com o argumento `label = after_stat(count)` e a função `geom_text`;\n+ Modificamos o **tema** do gráfico para obter uma alteração geral na aparência da figura. Existem diversos outros temas possíveis que podem ser vistos [aqui](https://ggplot2.tidyverse.org/reference/ggtheme.html).\n\nUm histograma com a frequência relativa pode ser obtido com:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(res, aes(x = CPUE,\n                y = after_stat(count)/sum(after_stat(count)),\n                label = round(after_stat(count)/sum(after_stat(count)), 2))) +\n  geom_histogram(breaks = cl_cpue, \n                 fill = 'darkblue', color = 'white') +\n  labs(x = 'Captura em kg', y = 'Frequência relativa') +\n  geom_text(stat = \"bin\", size = 6, vjust = 1.5, color = 'white',\n            breaks = cl_cpue) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](varquant_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n\nAqui fizemos duas mudanças:\n+ Inserimos o argumento `y = after_stat(count)/sum(after_stat(count))` para dizer que as barras em $y$ devem mostrar a contagem do número de observações em cada intervalo dividido pelo total;\n+ Modificamos o argumento `label = round(after_stat(count)/sum(after_stat(count)), 2)` de modo que também mostre a frequência relativa, utilizando a função `round`.\n\n### Representando frequências acumuladas\n\nA única modificação neste caso será identificarmos o eixo $y$ por sua contagem acumulada: `y = cumsum(after_stat(count))`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(res, aes(x = CPUE,\n                y = cumsum(after_stat(count)),\n                label = round(cumsum(after_stat(count)), 2))) +\n  geom_histogram(breaks = cl_cpue, \n                 fill = 'darkblue', color = 'white') +\n  labs(x = 'Captura em kg', y = 'Frequência acumulada') +\n  geom_text(stat = \"bin\", size = 6, vjust = 1.5, color = 'white',\n            breaks = cl_cpue) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](varquant_files/figure-html/unnamed-chunk-21-1.png){width=672}\n:::\n:::\n\n\n\n\nPara fazer o mesmo mostrando as frequências relativas, fazemos:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(res, aes(x = CPUE,\n                y = cumsum(after_stat(count)/sum(after_stat(count))),\n                label = round(cumsum(after_stat(count)/sum(after_stat(count))), 2))) +\n  geom_histogram(breaks = cl_cpue, \n                 fill = 'darkblue', color = 'white') +\n  labs(x = 'Captura em kg', y = 'Frequência acumulada relativa') +\n  geom_text(stat = \"bin\", size = 6, vjust = 1.5, color = 'white',\n            breaks = cl_cpue) +\n  theme_classic()\n```\n\n::: {.cell-output-display}\n![](varquant_files/figure-html/unnamed-chunk-22-1.png){width=672}\n:::\n:::",
    "supporting": [
      "varquant_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}