{
  "hash": "0da895abb6d24591513b822025b64932",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Regressão linear múltipla\"\nauthor: baseado no livro [Experimental Design and Data Analysis for Biologists](https://www.cambridge.org/highereducation/books/experimental-design-and-data-analysis-for-biologists/BAF276114278FF40A7ED1B0FE77D691A#overview){target=\"_blank\"}\ndescription: \"Regressão linear múltipla, discutindo seleção de variáveis, pressupostos e diagnósticos de adequação do modelo.\"\nCategories: [\n          \"Regressão linear\",\n          \"Estatística\"\n        ]\n\nimage: \"images/regressao-linear-multipla.jpg\"\nexecute:\n  echo: true\n  warning: false\n  include: true\n  message: false\n---\n\n\n\n\n:::{.callout-tip collapse=\"true\"}\n## Pacotes, funções e base de dados utilizadas\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(GGally)\nlibrary(patchwork)\nlibrary(gt)\n```\n:::\n\n\n\n\n:::\n\n## Abundância de aves em fragmentos de floresta\n\n@loyn1987effects conduziu um estudo para entender quais características do habitat estavam relacionadas à abundância de aves da floresta (acesse o artigo <a href=\"https://github.com/FCopf/datasets/blob/main/Loyn1987fragments.pdf\" target=\"_blank\">aqui</a>). Para isso, ele selecionou 56 fragmentos de floresta no sudeste de Victoria, Austrália, e registrou a abundância de aves da floresta (**ABUND**) em cada fragmento como variável de resposta.\n\nAs variáveis preditoras registradas para cada fragmento incluíram:\n\n- Área do fragmento (ha): **AREA**\n- Distância ao fragmento mais próximo (km): **DIST**\n- Distância ao fragmento maior mais próximo (km):**LDIST**\n- Número de anos desde que o fragmento foi isolado por desmatamento (anos):**YR.ISOL**\n- Índice de histórico de pastagem, de 1 (leve) a 5 (pesado):**GRAZE**\n- Altitude média (m):**ALT**\n\nInicialmente, vamos nos concentrar nas variáveis **YR.ISOL**, **GRAZE** e **ALT**.\n\n\nImporte a base de dados `loyn.csv`\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloyn = read_csv(\"https://raw.githubusercontent.com/FCopf/datasets/refs/heads/main/loyn.csv\")\n\nhead(loyn) |> gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"cnjvdqifdj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#cnjvdqifdj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#cnjvdqifdj thead, #cnjvdqifdj tbody, #cnjvdqifdj tfoot, #cnjvdqifdj tr, #cnjvdqifdj td, #cnjvdqifdj th {\n  border-style: none;\n}\n\n#cnjvdqifdj p {\n  margin: 0;\n  padding: 0;\n}\n\n#cnjvdqifdj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#cnjvdqifdj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#cnjvdqifdj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#cnjvdqifdj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#cnjvdqifdj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cnjvdqifdj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cnjvdqifdj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#cnjvdqifdj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#cnjvdqifdj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#cnjvdqifdj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#cnjvdqifdj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#cnjvdqifdj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#cnjvdqifdj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#cnjvdqifdj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#cnjvdqifdj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#cnjvdqifdj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#cnjvdqifdj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#cnjvdqifdj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#cnjvdqifdj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cnjvdqifdj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#cnjvdqifdj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#cnjvdqifdj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#cnjvdqifdj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cnjvdqifdj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#cnjvdqifdj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#cnjvdqifdj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cnjvdqifdj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cnjvdqifdj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#cnjvdqifdj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cnjvdqifdj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#cnjvdqifdj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#cnjvdqifdj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cnjvdqifdj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cnjvdqifdj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#cnjvdqifdj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#cnjvdqifdj .gt_left {\n  text-align: left;\n}\n\n#cnjvdqifdj .gt_center {\n  text-align: center;\n}\n\n#cnjvdqifdj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#cnjvdqifdj .gt_font_normal {\n  font-weight: normal;\n}\n\n#cnjvdqifdj .gt_font_bold {\n  font-weight: bold;\n}\n\n#cnjvdqifdj .gt_font_italic {\n  font-style: italic;\n}\n\n#cnjvdqifdj .gt_super {\n  font-size: 65%;\n}\n\n#cnjvdqifdj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#cnjvdqifdj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#cnjvdqifdj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#cnjvdqifdj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#cnjvdqifdj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#cnjvdqifdj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#cnjvdqifdj .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#cnjvdqifdj .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#cnjvdqifdj div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ABUND\">ABUND</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"AREA\">AREA</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"YR.ISOL\">YR.ISOL</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"DIST\">DIST</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"LDIST\">LDIST</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"GRAZE\">GRAZE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"ALT\">ALT</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"ABUND\" class=\"gt_row gt_right\">5.3</td>\n<td headers=\"AREA\" class=\"gt_row gt_right\">0.1</td>\n<td headers=\"YR.ISOL\" class=\"gt_row gt_right\">1968</td>\n<td headers=\"DIST\" class=\"gt_row gt_right\">39</td>\n<td headers=\"LDIST\" class=\"gt_row gt_right\">39</td>\n<td headers=\"GRAZE\" class=\"gt_row gt_right\">2</td>\n<td headers=\"ALT\" class=\"gt_row gt_right\">160</td></tr>\n    <tr><td headers=\"ABUND\" class=\"gt_row gt_right\">2.0</td>\n<td headers=\"AREA\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"YR.ISOL\" class=\"gt_row gt_right\">1920</td>\n<td headers=\"DIST\" class=\"gt_row gt_right\">234</td>\n<td headers=\"LDIST\" class=\"gt_row gt_right\">234</td>\n<td headers=\"GRAZE\" class=\"gt_row gt_right\">5</td>\n<td headers=\"ALT\" class=\"gt_row gt_right\">60</td></tr>\n    <tr><td headers=\"ABUND\" class=\"gt_row gt_right\">1.5</td>\n<td headers=\"AREA\" class=\"gt_row gt_right\">0.5</td>\n<td headers=\"YR.ISOL\" class=\"gt_row gt_right\">1900</td>\n<td headers=\"DIST\" class=\"gt_row gt_right\">104</td>\n<td headers=\"LDIST\" class=\"gt_row gt_right\">311</td>\n<td headers=\"GRAZE\" class=\"gt_row gt_right\">5</td>\n<td headers=\"ALT\" class=\"gt_row gt_right\">140</td></tr>\n    <tr><td headers=\"ABUND\" class=\"gt_row gt_right\">17.1</td>\n<td headers=\"AREA\" class=\"gt_row gt_right\">1.0</td>\n<td headers=\"YR.ISOL\" class=\"gt_row gt_right\">1966</td>\n<td headers=\"DIST\" class=\"gt_row gt_right\">66</td>\n<td headers=\"LDIST\" class=\"gt_row gt_right\">66</td>\n<td headers=\"GRAZE\" class=\"gt_row gt_right\">3</td>\n<td headers=\"ALT\" class=\"gt_row gt_right\">160</td></tr>\n    <tr><td headers=\"ABUND\" class=\"gt_row gt_right\">13.8</td>\n<td headers=\"AREA\" class=\"gt_row gt_right\">1.0</td>\n<td headers=\"YR.ISOL\" class=\"gt_row gt_right\">1918</td>\n<td headers=\"DIST\" class=\"gt_row gt_right\">246</td>\n<td headers=\"LDIST\" class=\"gt_row gt_right\">246</td>\n<td headers=\"GRAZE\" class=\"gt_row gt_right\">5</td>\n<td headers=\"ALT\" class=\"gt_row gt_right\">140</td></tr>\n    <tr><td headers=\"ABUND\" class=\"gt_row gt_right\">14.1</td>\n<td headers=\"AREA\" class=\"gt_row gt_right\">1.0</td>\n<td headers=\"YR.ISOL\" class=\"gt_row gt_right\">1965</td>\n<td headers=\"DIST\" class=\"gt_row gt_right\">234</td>\n<td headers=\"LDIST\" class=\"gt_row gt_right\">285</td>\n<td headers=\"GRAZE\" class=\"gt_row gt_right\">3</td>\n<td headers=\"ALT\" class=\"gt_row gt_right\">130</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n## Gráficos de dispersão entre ABUND e cada uma das demais variáveis preditoras\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplt_gr <- ggplot(loyn) +\n  aes(y = ABUND, x = GRAZE) +\n  geom_point() +\n  geom_smooth(se = FALSE, span = 1)\n\nplt_al <- ggplot(loyn) +\n  aes(y = ABUND, x = ALT) +\n  geom_point() +\n  geom_smooth(se = FALSE, span = 1)\n\nplt_yr <- ggplot(loyn) +\n  aes(y = ABUND, x = YR.ISOL) +\n  geom_point() +\n  geom_smooth(se = FALSE, span = 1)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplt_gr + plt_al + plt_yr\n```\n\n::: {.cell-output-display}\n![](regressao-linear-multipla_files/figure-html/unnamed-chunk-4-1.png){width=768}\n:::\n:::\n\n\n\n\n## Multicolinearidade: as variáveis preditoras são correlacionadas entre si?\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggpairs(loyn |> select(GRAZE, ALT, YR.ISOL))\n```\n\n::: {.cell-output-display}\n![](regressao-linear-multipla_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\n\n\nAs variáveis **ALT** versus **GRAZE** e **GRAZE** versus **YR.ISOL** parecem ter um grau de correlação moderado entre si.\n\n## O modelo de regressão múltipla\n\nO modelo de regressão linear múltipla é dado por:\n\n$$ABUND_i = \\beta_0 + \\beta_1 ALT_i + \\beta_2 YR.ISIOL_i + \\epsilon_i$$\n\nNo R pode ser ajustado por:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmfull <- lm(ABUND ~ ALT + YR.ISOL, data  = loyn)\nmfull\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ABUND ~ ALT + YR.ISOL, data = loyn)\n\nCoefficients:\n(Intercept)          ALT      YR.ISOL  \n -348.47698      0.07006      0.18348  \n```\n\n\n:::\n:::\n\n\n\n\nO resumo do modelo pode ser visto com a função `summary`\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(mfull)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ABUND ~ ALT + YR.ISOL, data = loyn)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-18.9745  -6.4690   0.6168   7.4408  24.0155 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -348.47698   93.73407  -3.718 0.000486 ***\nALT            0.07006    0.02852   2.457 0.017329 *  \nYR.ISOL        0.18348    0.04852   3.781 0.000398 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 8.953 on 53 degrees of freedom\nMultiple R-squared:  0.3297,\tAdjusted R-squared:  0.3044 \nF-statistic: 13.03 on 2 and 53 DF,  p-value: 2.49e-05\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n## Hipótese nula e comparação de modelos\n\nA hipótese nula ($H_0$) básica que podemos testar ao ajustar um modelo de regressão linear múltipla é que todas as inclinações de regressão parciais são iguais a zero, ou seja, $H_0: \\beta_1 = \\beta_2 = \\cdots = \\beta_j = 0$. Neste exemplo, $H_0$ é que o coeficiente de inclinação dos níveis de pastagem e os anos de isolamento do fragmento sejam ambos iguais a zero e, consequentemente, não têm influência sobre a abundância.\n\nTestamos a hipótese nula com a ANOVA na regressão múltipla, que divide a variação total de $Y$ em dois componentes: a variação explicada pela regressão linear com $X_1$, $X_2$, $\\cdots$, $X_j$ e a variação residual.\n\nSe $H_0$ for verdadeira, tanto o quadrado médio da regressão $QM_{Regressão}$ quanto o quadrado médio do resíduo ($QM_{Resíduo}$) estimarão $\\sigma^2$, e a razão $F$ entre eles será igual a 1. Se $H_0$ for falsa, pelo menos uma das inclinações de regressão parciais não será igual a zero e $QM_{Regressão}$ estimará $\\sigma^2$ mais um termo $QM_{Regressão}$ o que representa essas inclinações de regressão parciais. Portanto, a razão $F = \\frac{QM_{Regressão}}{QM_{Regressão}} > 1$. Neste caso, a decisão de aceitar $H_0$ é feita pela comparação do $F$ calculado com a distribuição $F$ apropriada, da mesma forma que fazemos com a regressão linear simples ou com a Análise de Variância.\n\nO resultado da razão $F$ aparece no comando `summary`, que no exemplo acima é F = 13.035, com valor de p = 2.5\\times 10^{-5}.\n\nTambém podemos testar as hipóteses nulas sobre cada coeficiente de regressão parcial, ou seja, de que qualquer $\\beta_1$ seja igual a zero. Para isto, podemos usar a estratégia de comparação de modelos em que o modelo completo (aquele com todas as variáveis) é comparado com o modelo reduzido (aquele sem a variável $X_1$ de interesse).\n\nPara testar o efeito da altitude, por exemplo, o modelo reduzido é:\n\n$ABUND_i = \\beta_0 + \\beta_2 YR.ISIOL_i + \\epsilon_i$\n\nO modelo completo tem soma dos quadrados ($SQ$) maior que o modelo reduzido. Para comparar o ganho extra que o modelo completo tem sobre o modelo reduzido podemos fazer:\n\n$SS_{extra} = SS_{Regressão_{completo}} - SS_{Regressão_{reduzido}}$\n\nEm seguida, calculamos o quadrado médio extra como $QM_{extra} = \\frac{SS_{extra}}{gl}$ e usamos o teste $F$ como:\n\n$F = \\frac{QM_{extra}}{QM_{Resíduo_{completo}}}$\n\nO mesmo pode ser feito para a variável $YR.ISOL$.\n\nNo R, podemos testar os efeitos dos coeficientes parciais de regressão com o comando `drop1`.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndrop1(mfull, test = 'F')\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSingle term deletions\n\nModel:\nABUND ~ ALT + YR.ISOL\n        Df Sum of Sq    RSS    AIC F value    Pr(>F)    \n<none>               4248.3 248.42                      \nALT      1    483.79 4732.1 252.46  6.0355 0.0173292 *  \nYR.ISOL  1   1146.10 5394.4 259.80 14.2982 0.0003979 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n\n\nVemos aqui que os dois componentes (**ALT** e **YR.ISOL**) adicionam uma variação explicada significativa, isto é, para os dois coeficientes $p \\le 0,005$.\n\nNote que o teste o teste F de comparação de modelos foi equivalente ao teste $t$ aplicado a cada coeficiente e que pode ser visto no resultado da função summary, sendo $F = t^2$. No entanto, a estratégia de comparação de modelos apresentada aqui permite a comparação não somente de coeficientes isolados, mas de qualquer combinação específica dos coeficientes em comparação com o modelo completo.\n\n## Coeficiente de determinação ($R^2$)\n\nNa regressão múltipla, o coeficiente de determinação $R^2$ mede a proporção da variabilidade total da variável resposta que é explicada pelas variáveis preditoras. No entanto, $R^2$ tende a aumentar à medida que mais preditores são adicionados ao modelo, mesmo que não sejam significativos. Para corrigir essa inflação, utilizamos o coeficiente de determinação ajustado ($R^2_{ajustado}$), que ajusta o $R^2$ considerando o número de preditores no modelo e o tamanho da amostra. O $R^2_{ajustado}$ penaliza a adição de preditores irrelevantes, proporcionando uma avaliação mais precisa da qualidade do ajuste do modelo e pode ser obtido pela expressão:\n\n$R^2_{ajustado} = 1 - \\frac{(1-R^2)(n-1)}{n-k-1}$\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nNo resultado da função `summary` vemos que o $R^2 = 0.33$ e o $R^2_{ajustado} = 0.304$.\n\n## Pressupostos da regressão linear múltipla\n\n### Normalidade dos resíduos\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloyn <- loyn |> \n  mutate(rst = rstudent(mfull),\n         yaj = fitted(mfull))\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(loyn) +\n  aes(x = rst, y = after_stat(density)) +\n  geom_histogram(bins = 10, density = TRUE, color = 'white') +\n  geom_density(color = 'darkblue', linewidth = 2)\n```\n\n::: {.cell-output-display}\n![](regressao-linear-multipla_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nshapiro.test(loyn$rst)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tShapiro-Wilk normality test\n\ndata:  loyn$rst\nW = 0.97409, p-value = 0.2687\n```\n\n\n:::\n:::\n\n\n\n\n### Gráfico de resíduos\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(loyn) +\n  aes(x = yaj, y = rst) +\n  geom_point() +\n  geom_hline(yintercept = 0, linetype = \"dashed\", color = \"blue\")\n```\n\n::: {.cell-output-display}\n![](regressao-linear-multipla_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\n### Índice de Alavancagem (Leverage)\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninfl <- influence.measures(mfull)$infmat |> \n  as.data.frame()\n\nggplot(infl) +\n  aes(y = hat, x = 1:nrow(infl)) +\n  geom_point() +\n  ylab('Leverage')\n```\n\n::: {.cell-output-display}\n![](regressao-linear-multipla_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n\n### Índice de Alavancagem de Cook (Dcook)\n\nO índice de alavancagem de Cook é uma medida que combina a magnitude do efeito de alavancagem de uma observação com o quanto essa observação influencia a estimativa dos coeficientes de regressão. Uma observação com $D_{Cook} > 1$ é frequentemente considerada influente e devem ser examinada para avaliar seu impacto no modelo.\n\nPara obter o índice de alavancagem de Cook em R:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(infl) +\n  aes(y = cook.d, x = 1:nrow(infl)) +\n  geom_point() +\n  ylab('Distância de Cook')\n```\n\n::: {.cell-output-display}\n![](regressao-linear-multipla_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n:::\n\n\n\n\n## Outros dignósticos\n\n### Resíduos *versus* variáveis preditoras\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(loyn) +\n  aes(x = ALT, y = rst) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](regressao-linear-multipla_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(loyn) +\n  aes(x = YR.ISOL, y = rst) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](regressao-linear-multipla_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n:::\n\n\n\n\n### Resíduos dos modelos reduzidos versus variáveis preditoras\n\nNeste gráficos, ajustamos os modelos reduzidos excluindo uma variável preditora por vez e plotamos os resíduos deste modelo com a variável preditora excluída. Uma tendência neste gráfico indica que a inclusão da variável no modelo ajudaria a reduzir a variação residual.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmpalt <- lm(ABUND ~ YR.ISOL, data  = loyn) # Modelo reduzido sem ALT\nplot(rstudent(mpalt) ~ loyn$ALT)\nabline(lm(rstudent(mpalt) ~ loyn$ALT))\n```\n\n::: {.cell-output-display}\n![](regressao-linear-multipla_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nmpisol <- lm(ABUND ~ ALT, data  = loyn) # Modelo reduzido sem YR.ISOL\nplot(rstudent(mpisol) ~ loyn$YR.ISOL)\nabline(lm(rstudent(mpisol) ~ loyn$YR.ISOL))\n```\n\n::: {.cell-output-display}\n![](regressao-linear-multipla_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n:::\n\n\n\n\n## Mais sobre multicolinearidade\n\nVariáveis preditoras correlacionadas entre si caracteriza a multicolinearidade. Quando severa, a multicolinearidade pode afetar a estimativa dos parâmetros da regressão, pois pequenas alterações nos dados ou inclusão/remoção de variáveis podem causar grandes mudanças nos coeficientes estimados da regressão. Além disso, a presença de multicolinearidade pode inflar os erros padrões dos coeficientes de regressão, resultando em um modelo globalmente significativo, mas com coeficientes individuais que não são estatisticamente diferentes de zero.\n\nAvaliar uma matriz de correlação entre pares de variáveis preditoras pode ser a primeira e mais simples forma de explorar a presença de colinearidade. Outra forma é avaliar a tolerância de cada variável preditora $X_j$ por meio de $1 - R^2_j$, em que $R^2_j$ é o coeficiente de determinação do modelo em que $X_j$ é relacionada às demais $1 - p$ variáveis preditoras. Geralmente, esta tolerância é expressa na forma do índice de inflação da variação (*variance inflation factor* - $VIF$) para cada variável preditora, em que:\n\n$$VIF_j =\\frac{1}{1 - R^2_j}$$\n\nValores elevados indicam que a presença de colinearidade devido a variável $X_j$. Diferente níveis de corte são propostos como indicadores da presença de multicolinearidade $VIF > 5$, $VIF > 10$ ou $VIF > 20$\n\nTodos os coeficientes $VIF_j$ podem ser encontrados em uma única operação calculando a inversa da matriz de correlação, $\\mathbb{R^{1}}$ entre as variáveis de interesse. Os elementos diagonais dessa matriz inversa são os coeficientes $VIF_j$. Vimos que **GRAZE** era correlacionada com **ALT** e com **YR.ISOL**. Os ceoficientes $VIF$ para estas variáveis podem ser obtidos por:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif <- loyn |> \n  select(GRAZE, ALT, YR.ISOL) |> \n  cor() |> \n  solve() |> \n  diag()\n\nvif\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   GRAZE      ALT  YR.ISOL \n1.904799 1.200372 1.679995 \n```\n\n\n:::\n:::\n\n\n\n\nO $VIF$ para **GRAZE** é maior que os demais, porém longe do limite $VIF > 5$. Vejamos entretanto o que ocorre com o modelo para abundância se inserimos estas três variáveis:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmfull2 <- lm(ABUND ~ GRAZE + ALT + YR.ISOL, data = loyn)\nsummary(mfull2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ABUND ~ GRAZE + ALT + YR.ISOL, data = loyn)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-19.5498  -4.8951   0.6504   4.7798  20.2384 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -73.58185  107.24995  -0.686 0.495712    \nGRAZE        -4.01692    0.99881  -4.022 0.000188 ***\nALT           0.03285    0.02679   1.226 0.225618    \nYR.ISOL       0.05143    0.05393   0.954 0.344719    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 7.894 on 52 degrees of freedom\nMultiple R-squared:  0.4887,\tAdjusted R-squared:  0.4592 \nF-statistic: 16.57 on 3 and 52 DF,  p-value: 1.106e-07\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\nNote que agora, somente **GRAZE** aparece com coeficiente estatísticamente diferente de $0$ e $R^2_{ajustado}$ aumenta de 0.304 para 0.459\n\n## Tranformações\n\nTransformações podem frequentemente ser eficazes se a distribuição em situações em que as variáveis preditoras apresentem distribuições assimétricas. Vamos incluir a **AREA** no modelo de regressão. Vejamos os graficos de disperção entre as variáveis preditoras.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggpairs(loyn |> select(AREA, GRAZE, ALT, YR.ISOL))\n```\n\n::: {.cell-output-display}\n![](regressao-linear-multipla_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n\n\nHá uma relação fortemente assimétrica da variável área, em que poucos framentos são muito maiores. Vejamos as associações par a par utilizando a transfomação $log(AREA)$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nloyn$lAREA <- log(loyn$AREA)\nggpairs(loyn |> select(lAREA, GRAZE, ALT, YR.ISOL))\n```\n\n::: {.cell-output-display}\n![](regressao-linear-multipla_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\n\n\n\nA transformação resolveu o problema da assimetria.\n\nVamos ajustar agora o modelo de regressão:\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmfull3 <- lm(ABUND ~ lAREA + GRAZE + ALT + YR.ISOL, data = loyn)\nsummary(mfull3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = ABUND ~ lAREA + GRAZE + ALT + YR.ISOL, data = loyn)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-14.4245  -3.3341   0.6227   2.6759  15.3290 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -141.88574   86.23728  -1.645   0.1061    \nlAREA          3.07303    0.55118   5.575 9.41e-07 ***\nGRAZE         -1.60127    0.90538  -1.769   0.0829 .  \nALT            0.02586    0.02136   1.210   0.2317    \nYR.ISOL        0.07991    0.04323   1.848   0.0703 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 6.283 on 51 degrees of freedom\nMultiple R-squared:  0.6823,\tAdjusted R-squared:  0.6574 \nF-statistic: 27.39 on 4 and 51 DF,  p-value: 3.671e-12\n```\n\n\n:::\n:::\n\n\n\n\nO resultado indica que somente o $log(AREA)$ seja importante para predizer a abundância. Entretanto, lembre-se que havia uma certo padrão de colinearidade entre **GRAZE**, **ALT** a **YR.ISOL**. Teste retirar uma a uma estas variáveis do modelo e avalie os resultados.",
    "supporting": [
      "regressao-linear-multipla_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}