{
  "hash": "1c962845d7c9b0fa14d6c37ec88681bd",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Partição da soma dos quadrados e coeficiente de determinação na regressão linear\"\ndescription: \"Decomposição da variabilidade total em componentes da regressão e do resíduo. Derivação e interpretação do coeficiente de determinação $R^2$.\"\ncategories: [\n          \"Regressão linear\",\n          \"Estatística\",\n          \"Soma dos quadrados\",\n          \"Coeficiente de determinação\"\n        ]\n\nimage: \"images/ss-partition-r2.jpg\"\nexecute:\n  echo: true\n  warning: false\n  include: true\n  message: false\n---\n\n\n\n::: {.callout-tip collapse=\"true\"}\n## Pacotes e funções utilizadas no capítulo\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(patchwork)\nlibrary(gt)\nlibrary(knitr)\n```\n:::\n\n\n:::\n\nAo ajustar um modelo de regressão linear simples, obtemos a reta que minimiza a soma dos quadrados dos resíduos ($SQ_{Res}$). Um aspecto fundamental deste processo consiste em compreender **qual a proporção da variação total em** $Y$ o modelo é capaz de explicar? Para responder a esta pergunta, precisamos decompor a variação total de $Y$ em duas parcelas distintas: uma atribuída à regressão e outra atribuída aos resíduos. Este processo é conhecido como **partição da soma dos quadrados**.\n\nRecordando o modelo de regressão linear simples:\n\n$$Y_i = \\hat{\\beta}_0 + \\hat{\\beta}_1 X_i + e_i$$\n\nonde $\\hat{Y}_i = \\hat{\\beta}_0 + \\hat{\\beta}_1 X_i$ é o valor **ajustado** e $e_i = Y_i - \\hat{Y}_i$ é o **resíduo** da $i$-ésima observação.\n\n## Os três componentes da variação\n\nConsideremos $n$ pares de observações $(X_i, Y_i)$ com $i = 1, \\ldots, n$. Definimos três quantidades fundamentais.\n\n**Soma dos Quadrados Total** ($SQ_{Total}$): mede a variação total de $Y$ em torno de sua média $\\bar{Y}$, independentemente do modelo de regressão.\n\n$$SQ_{Total} = \\sum_{i=1}^{n}(Y_i - \\bar{Y})^2$$\n\n**Soma dos Quadrados da Regressão** ($SQ_{Reg}$): mede a variação nos valores **ajustados** $\\hat{Y}_i$ em torno de $\\bar{Y}$. Representa a parcela da variação total que é *explicada* pela variável preditora $X$.\n\n$$SQ_{Reg} = \\sum_{i=1}^{n}(\\hat{Y}_i - \\bar{Y})^2$$\n\n**Soma dos Quadrados dos Resíduos** ($SQ_{Res}$): mede a variação dos valores observados em torno dos valores ajustados. Representa a parcela da variação total que *não* é explicada pelo modelo, atribuída ao erro.\n\n$$SQ_{Res} = \\sum_{i=1}^{n}(Y_i - \\hat{Y}_i)^2$$\n\n::: callout-note\n## As três somas dos quadrados\n\n| Componente | Expressão | Interpretação |\n|:-----------------|:-----------------------------|:------------------------|\n| $SQ_{Total}$ | $\\sum (Y_i - \\bar{Y})^2$ | Variação total em $Y$ |\n| $SQ_{Reg}$ | $\\sum (\\hat{Y}_i - \\bar{Y})^2$ | Variação explicada pelo modelo |\n| $SQ_{Res}$ | $\\sum (Y_i - \\hat{Y}_i)^2$ | Variação não explicada (resíduo) |\n:::\n\nA figura abaixo ilustra os três desvios para uma observação qualquer $(X_k, Y_k)$.\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](particao-soma-quadrados-r2_files/figure-html/unnamed-chunk-2-1.png){fig-align='center' width=672}\n:::\n:::\n\n\n\nA linha tracejada horizontal representa $\\bar{Y}$. Para o ponto destacado, podemos observar:\n\n-   O desvio total ($Y_k - \\bar{Y}$, em preto) é a soma do desvio da regressão e do resíduo.\n-   O desvio da regressão ($\\hat{Y}_k - \\bar{Y}$, em verde) é a porção do desvio total capturada pelo modelo.\n-   O resíduo ($Y_k - \\hat{Y}_k$, em vermelho) é o que sobra após o ajuste.\n\nUma propriedade da decomposição da soma dos quadrados é que $SQ_{Total} = SQ_{Reg} + SQ_{Res}$ portanto:\n\n::: callout-note\n## Partição da soma dos quadrados na regressão linear\n\n$$SQ_{Total} = SQ_{Reg} + SQ_{Res}$$\n\n$$\\sum_{i=1}^{n}(Y_i - \\bar{Y})^2 = \\sum_{i=1}^{n}(\\hat{Y}_i - \\bar{Y})^2 + \\sum_{i=1}^{n}(Y_i - \\hat{Y}_i)^2$$\n:::\n\n## O coeficiente de determinação $R^2$\n\n### Definição e interpretação\n\nA partição da soma dos quadrados nos permite definir o **coeficiente de determinação** $R^2$ como a proporção da variação total em $Y$ que é explicada pelo modelo de regressão:\n\n::: callout-note\n## Coeficiente de determinação\n\n$$R^2 = \\frac{SQ_{Reg}}{SQ_{Total}} = 1 - \\frac{SQ_{Res}}{SQ_{Total}}$$\n:::\n\nComo $0 \\le SQ_{Reg} \\le SQ_{Total}$, temos $0 \\le R^2 \\le 1$.\n\n-   $R^2 = 0$: o modelo não explica nenhuma variação em $Y$; a reta ajustada é horizontal ($\\hat{\\beta}_1 = 0$) e $SQ_{Reg} = 0$.\n-   $R^2 = 1$: o modelo explica **toda** a variação em $Y$; todos os pontos estão exatamente sobre a reta de regressão e $SQ_{Res} = 0$.\n-   $0 < R^2 < 1$: situação usual, em que o modelo explica uma fração $R^2 \\times 100\\%$ da variação total.\n\n### Formulações alternativas\n\n$SQ_{Reg}$ pode ser expresso em termos dos coeficientes do modelo e dos somatórios dos quadrados. Como $\\hat{Y}_i - \\bar{Y} = \\hat{\\beta}_1(X_i - \\bar{X})$:\n\n$$SQ_{Reg} = \\sum_{i=1}^{n}(\\hat{Y}_i - \\bar{Y})^2 = \\hat{\\beta}_1^2 \\sum_{i=1}^{n}(X_i - \\bar{X})^2 = \\hat{\\beta}_1^2 \\cdot SQ_X$$\n\nSubstituindo $\\hat{\\beta}_1 = SQ_{XY}/SQ_X$:\n\n$$SQ_{Reg} = \\frac{SQ_{XY}^2}{SQ_X^2} \\cdot SQ_X = \\frac{SQ_{XY}^2}{SQ_X} = \\hat{\\beta}_1 \\cdot SQ_{XY}$$\n\nonde $SQ_{XY} = \\sum(X_i - \\bar{X})(Y_i - \\bar{Y})$ é o produto cruzado de $X$ e $Y$, e $SQ_X = \\sum(X_i - \\bar{X})^2$.\n\n### Relação com o coeficiente de correlação\n\nNa regressão linear **simples**, $R^2$ é exatamente igual ao quadrado do coeficiente de correlação de Pearson $r$:\n\n$$R^2 = r^2$$\n\n**Demonstração.** Partindo de $R^2 = SQ_{Reg}/SQ_{Total} = SQ_{XY}^2 / (SQ_X \\cdot SQ_Y)$:\n\n$$R^2 = \\frac{SQ_{XY}^2}{SQ_X \\cdot SQ_Y} = \\left(\\frac{SQ_{XY}}{\\sqrt{SQ_X \\cdot SQ_Y}}\\right)^2 = r^2$$\n\n> Esta relação é exclusiva da regressão simples. Na regressão **múltipla**, $R^2$ generaliza o conceito de correlação, mas não é simplesmente o quadrado de uma correlação bivariada.\n\n### Limitações do $R^2$\n\nEmbora $R^2$ seja uma medida de ajuste amplamente utilizada, é importante reconhecer suas limitações:\n\n1.  $R^2$ não mede causalidade. Uma associação forte entre $Y$ e $X$ não implica que $X$ cause $Y$. Uma terceira variável pode ser responsável pela associação observada.\n\n2.  $R^2$ depende da amplitude de $X$. Ampliar o intervalo dos valores de $X$ tende a aumentar $SQ_{Reg}$ e, consequentemente, $R^2$, mesmo que a dispersão ao redor da reta não mude.\n\n3.  $R^2$ alto não garante bom ajuste. Um modelo pode ter $R^2$ elevado e ainda apresentar padrões sistemáticos nos resíduos, indicando violação de suposições do modelo.\n\n4.  $R^2$ baixo não invalida o modelo. Em muitas aplicações nas ciências biológicas e sociais, $R^2$ moderados (0,3–0,5) já refletem relações substantivas e interpretáveis.\n\n5.  $R^2$ não é comparável entre conjuntos de dados. Dois modelos com $R^2$ iguais em datasets diferentes não têm necessariamente a mesma qualidade de ajuste.\n\n## Situações extremas\n\nPara compreender melhor o significado de $R^2$, vamos simular dois cenários contrastantes: um com $R^2$ elevado e outro com $R^2$ baixo.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nn_sim <- 60\nX_sim <- seq(1, 10, length.out = n_sim)\ny_det <- 5 + 3 * X_sim\n\n# Cenário 1: R² alto (dispersão pequena em torno da reta)\nY_alto <- y_det + rnorm(n_sim, sd = 1.5)\n\n# Cenário 2: R² baixo (dispersão grande em torno da reta)\nY_baixo <- y_det + rnorm(n_sim, sd = 12)\n```\n:::\n\n\n\n### Cenário com $R^2$ elevado\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_alto <- data.frame(X = X_sim, Y = Y_alto)\nmod_alto <- lm(Y ~ X, data = df_alto)\n\n# Cálculo manual das somas dos quadrados\nYbar_alto <- mean(Y_alto)\nYfit_alto <- fitted(mod_alto)\n\nSQTotal_alto <- sum((Y_alto - Ybar_alto)^2)\nSQReg_alto   <- sum((Yfit_alto - Ybar_alto)^2)\nSQRes_alto   <- sum((Y_alto - Yfit_alto)^2)\n\n# Verificação: SQTotal = SQReg + SQRes\ncat(\"SQTotal:\", round(SQTotal_alto, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSQTotal: 3870.97 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SQReg:\", round(SQReg_alto, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSQReg: 3773.89 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SQRes:\", round(SQRes_alto, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSQRes: 97.08 \n```\n\n\n:::\n\n```{.r .cell-code}\n# R² manual\nR2_alto_manual <- SQReg_alto / SQTotal_alto\ncat(\"R² (manual):\", round(R2_alto_manual, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR² (manual): 0.9749 \n```\n\n\n:::\n:::\n\n\n\n### Cenário com $R^2$ baixo\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_baixo <- data.frame(X = X_sim, Y = Y_baixo)\nmod_baixo <- lm(Y ~ X, data = df_baixo)\n\n# Cálculo manual das somas dos quadrados\nYbar_baixo <- mean(Y_baixo)\nYfit_baixo <- fitted(mod_baixo)\n\nSQTotal_baixo <- sum((Y_baixo - Ybar_baixo)^2)\nSQReg_baixo   <- sum((Yfit_baixo - Ybar_baixo)^2)\nSQRes_baixo   <- sum((Y_baixo - Yfit_baixo)^2)\n\n# Verificação: SQTotal = SQReg + SQRes\ncat(\"SQTotal:\", round(SQTotal_baixo, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSQTotal: 10346.4 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SQReg:\", round(SQReg_baixo, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSQReg: 3262.46 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SQRes:\", round(SQRes_baixo, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSQRes: 7083.93 \n```\n\n\n:::\n\n```{.r .cell-code}\n# R² manual\nR2_baixo_manual <- SQReg_baixo / SQTotal_baixo\ncat(\"R² (manual):\", round(R2_baixo_manual, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR² (manual): 0.3153 \n```\n\n\n:::\n:::\n\n\n\n### Visualização dos dois cenários\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](particao-soma-quadrados-r2_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=1152}\n:::\n:::\n\n\n\nEm ambos os cenários, a reta de regressão apresenta a mesma inclinação populacional ($\\beta_1 = 3$), o que produz valores de $SQ_{Reg}$ bastante semelhantes. A diferença fundamental reside na variância residual. Na figura à esquerda, os pontos estão fortemente concentrados em torno da reta, o que implica um $SQ_{Res}$ relativamente pequeno em comparação com a variação total ($SQ_{Total}$) e, consequentemente, um $R^2$ elevado ($SQ_{Res} = 97.08$, $R^2 = 0.975$). Em contraste, na figura à direita, observa-se maior dispersão dos pontos em torno da reta ajustada, resultando em um $SQ_{Res}$ mais elevado e, portanto, em um $R^2$ mais baixo ($SQ_{Res} = 7083.93$, $R^2 = 0.315$).\n\n\n## Exemplo aplicado: dados RIKZ\n\nVamos aplicar todos os conceitos ao conjunto de dados RIKZ, que contém medidas de riqueza de macro-fauna praial (número de espécies) e o índice de exposição às ondas (NAP) coletados em $45$ amostras ao longo da costa da Holanda [@zuur2009mixed].\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrikz <- read_csv('https://raw.githubusercontent.com/FCopf/datasets/refs/heads/main/RIKZ.csv')\n```\n:::\n\n\n\n### Ajuste do modelo\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmod_rikz <- lm(Richness ~ NAP, data = rikz)\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n\nO modelo ajustado é:\n\n$$\\widehat{Richness} = 6.686 + (-2.867) \\times NAP$$\n\n### Cálculo manual das somas dos quadrados\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn_rk     <- nrow(rikz)\nYbar_rk  <- mean(rikz$Richness)\nYfit_rk  <- fitted(mod_rikz)\nYres_rk  <- residuals(mod_rikz)\n\nSQTotal_rk <- sum((rikz$Richness - Ybar_rk)^2)\nSQReg_rk   <- sum((Yfit_rk - Ybar_rk)^2)\nSQRes_rk   <- sum(Yres_rk^2)\n\ncat(\"SQTotal:\", round(SQTotal_rk, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSQTotal: 1101.644 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SQReg:  \", round(SQReg_rk, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSQReg:   357.529 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"SQRes:  \", round(SQRes_rk, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSQRes:   744.115 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Verificação (SQReg + SQRes):\", round(SQReg_rk + SQRes_rk, 3), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nVerificação (SQReg + SQRes): 1101.644 \n```\n\n\n:::\n:::\n\n\n\nA tabela abaixo apresenta os primeiros valores da decomposição para cada observação:\n\n\n\n::: {#tbl-rikz-decomp .cell tbl-cap='Primeiros 10 valores da decomposição da soma dos quadrados (RIKZ). Ybar = média geral de Richness.'}\n\n```{.r .cell-code  code-fold=\"true\"}\nrikz |>\n  mutate(\n    Yfit  = Yfit_rk,\n    Yres  = Yres_rk,\n    dev_total = Richness - Ybar_rk,\n    dev_reg   = Yfit_rk - Ybar_rk,\n    dev_res   = Yres_rk\n  ) |>\n  select(Richness, NAP, Yfit, dev_total, dev_reg, dev_res) |>\n  round(3) |>\n  slice_head(n = 10) |>\n  gt() |>\n  cols_label(\n    Richness  = \"Richness\",\n    NAP       = \"NAP\",\n    Yfit      = gt::md(\"$\\\\hat{Y}_i$\"),\n    dev_total = gt::md(\"$Y_i - \\\\bar{Y}$\"),\n    dev_reg   = gt::md(\"$\\\\hat{Y}_i - \\\\bar{Y}$\"),\n    dev_res   = gt::md(\"$Y_i - \\\\hat{Y}_i$\")\n  ) |>\n  fmt_number(decimals = 3)\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"tpobacxifq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#tpobacxifq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#tpobacxifq thead, #tpobacxifq tbody, #tpobacxifq tfoot, #tpobacxifq tr, #tpobacxifq td, #tpobacxifq th {\n  border-style: none;\n}\n\n#tpobacxifq p {\n  margin: 0;\n  padding: 0;\n}\n\n#tpobacxifq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#tpobacxifq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#tpobacxifq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#tpobacxifq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#tpobacxifq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tpobacxifq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tpobacxifq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#tpobacxifq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#tpobacxifq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#tpobacxifq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#tpobacxifq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#tpobacxifq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#tpobacxifq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#tpobacxifq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#tpobacxifq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#tpobacxifq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#tpobacxifq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#tpobacxifq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#tpobacxifq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tpobacxifq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#tpobacxifq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#tpobacxifq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#tpobacxifq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tpobacxifq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#tpobacxifq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#tpobacxifq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tpobacxifq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tpobacxifq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#tpobacxifq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tpobacxifq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#tpobacxifq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#tpobacxifq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tpobacxifq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tpobacxifq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#tpobacxifq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#tpobacxifq .gt_left {\n  text-align: left;\n}\n\n#tpobacxifq .gt_center {\n  text-align: center;\n}\n\n#tpobacxifq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#tpobacxifq .gt_font_normal {\n  font-weight: normal;\n}\n\n#tpobacxifq .gt_font_bold {\n  font-weight: bold;\n}\n\n#tpobacxifq .gt_font_italic {\n  font-style: italic;\n}\n\n#tpobacxifq .gt_super {\n  font-size: 65%;\n}\n\n#tpobacxifq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#tpobacxifq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#tpobacxifq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#tpobacxifq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#tpobacxifq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#tpobacxifq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#tpobacxifq .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#tpobacxifq .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#tpobacxifq div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Richness\">Richness</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"NAP\">NAP</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Yfit\"><span data-qmd-base64=\"JFxoYXR7WX1faSQ=\"><span class='gt_from_md'>\\(\\hat{Y}_i\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dev_total\"><span data-qmd-base64=\"JFlfaSAtIFxiYXJ7WX0k\"><span class='gt_from_md'>\\(Y_i - \\bar{Y}\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dev_reg\"><span data-qmd-base64=\"JFxoYXR7WX1faSAtIFxiYXJ7WX0k\"><span class='gt_from_md'>\\(\\hat{Y}_i - \\bar{Y}\\)</span></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"dev_res\"><span data-qmd-base64=\"JFlfaSAtIFxoYXR7WX1faSQ=\"><span class='gt_from_md'>\\(Y_i - \\hat{Y}_i\\)</span></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Richness\" class=\"gt_row gt_right\">11.000</td>\n<td headers=\"NAP\" class=\"gt_row gt_right\">0.045</td>\n<td headers=\"Yfit\" class=\"gt_row gt_right\">6.557</td>\n<td headers=\"dev_total\" class=\"gt_row gt_right\">5.311</td>\n<td headers=\"dev_reg\" class=\"gt_row gt_right\">0.868</td>\n<td headers=\"dev_res\" class=\"gt_row gt_right\">4.443</td></tr>\n    <tr><td headers=\"Richness\" class=\"gt_row gt_right\">10.000</td>\n<td headers=\"NAP\" class=\"gt_row gt_right\">−1.036</td>\n<td headers=\"Yfit\" class=\"gt_row gt_right\">9.656</td>\n<td headers=\"dev_total\" class=\"gt_row gt_right\">4.311</td>\n<td headers=\"dev_reg\" class=\"gt_row gt_right\">3.967</td>\n<td headers=\"dev_res\" class=\"gt_row gt_right\">0.344</td></tr>\n    <tr><td headers=\"Richness\" class=\"gt_row gt_right\">13.000</td>\n<td headers=\"NAP\" class=\"gt_row gt_right\">−1.336</td>\n<td headers=\"Yfit\" class=\"gt_row gt_right\">10.516</td>\n<td headers=\"dev_total\" class=\"gt_row gt_right\">7.311</td>\n<td headers=\"dev_reg\" class=\"gt_row gt_right\">4.827</td>\n<td headers=\"dev_res\" class=\"gt_row gt_right\">2.484</td></tr>\n    <tr><td headers=\"Richness\" class=\"gt_row gt_right\">11.000</td>\n<td headers=\"NAP\" class=\"gt_row gt_right\">0.616</td>\n<td headers=\"Yfit\" class=\"gt_row gt_right\">4.920</td>\n<td headers=\"dev_total\" class=\"gt_row gt_right\">5.311</td>\n<td headers=\"dev_reg\" class=\"gt_row gt_right\">−0.769</td>\n<td headers=\"dev_res\" class=\"gt_row gt_right\">6.080</td></tr>\n    <tr><td headers=\"Richness\" class=\"gt_row gt_right\">10.000</td>\n<td headers=\"NAP\" class=\"gt_row gt_right\">−0.684</td>\n<td headers=\"Yfit\" class=\"gt_row gt_right\">8.647</td>\n<td headers=\"dev_total\" class=\"gt_row gt_right\">4.311</td>\n<td headers=\"dev_reg\" class=\"gt_row gt_right\">2.958</td>\n<td headers=\"dev_res\" class=\"gt_row gt_right\">1.353</td></tr>\n    <tr><td headers=\"Richness\" class=\"gt_row gt_right\">8.000</td>\n<td headers=\"NAP\" class=\"gt_row gt_right\">1.190</td>\n<td headers=\"Yfit\" class=\"gt_row gt_right\">3.274</td>\n<td headers=\"dev_total\" class=\"gt_row gt_right\">2.311</td>\n<td headers=\"dev_reg\" class=\"gt_row gt_right\">−2.415</td>\n<td headers=\"dev_res\" class=\"gt_row gt_right\">4.726</td></tr>\n    <tr><td headers=\"Richness\" class=\"gt_row gt_right\">9.000</td>\n<td headers=\"NAP\" class=\"gt_row gt_right\">0.820</td>\n<td headers=\"Yfit\" class=\"gt_row gt_right\">4.335</td>\n<td headers=\"dev_total\" class=\"gt_row gt_right\">3.311</td>\n<td headers=\"dev_reg\" class=\"gt_row gt_right\">−1.354</td>\n<td headers=\"dev_res\" class=\"gt_row gt_right\">4.665</td></tr>\n    <tr><td headers=\"Richness\" class=\"gt_row gt_right\">8.000</td>\n<td headers=\"NAP\" class=\"gt_row gt_right\">0.635</td>\n<td headers=\"Yfit\" class=\"gt_row gt_right\">4.865</td>\n<td headers=\"dev_total\" class=\"gt_row gt_right\">2.311</td>\n<td headers=\"dev_reg\" class=\"gt_row gt_right\">−0.824</td>\n<td headers=\"dev_res\" class=\"gt_row gt_right\">3.135</td></tr>\n    <tr><td headers=\"Richness\" class=\"gt_row gt_right\">19.000</td>\n<td headers=\"NAP\" class=\"gt_row gt_right\">0.061</td>\n<td headers=\"Yfit\" class=\"gt_row gt_right\">6.511</td>\n<td headers=\"dev_total\" class=\"gt_row gt_right\">13.311</td>\n<td headers=\"dev_reg\" class=\"gt_row gt_right\">0.822</td>\n<td headers=\"dev_res\" class=\"gt_row gt_right\">12.489</td></tr>\n    <tr><td headers=\"Richness\" class=\"gt_row gt_right\">17.000</td>\n<td headers=\"NAP\" class=\"gt_row gt_right\">−1.334</td>\n<td headers=\"Yfit\" class=\"gt_row gt_right\">10.510</td>\n<td headers=\"dev_total\" class=\"gt_row gt_right\">11.311</td>\n<td headers=\"dev_reg\" class=\"gt_row gt_right\">4.821</td>\n<td headers=\"dev_res\" class=\"gt_row gt_right\">6.490</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n### Verificação com funções do R\n\nAs somas dos quadrados podem ser extraídas diretamente da tabela ANOVA da regressão:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(mod_rikz)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAnalysis of Variance Table\n\nResponse: Richness\n          Df Sum Sq Mean Sq F value    Pr(>F)    \nNAP        1 357.53  357.53   20.66 4.418e-05 ***\nResiduals 43 744.12   17.31                      \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\nAs somas dos quadrados estão na coluna `Sum sq`. A primeira linha (`NAP`) corresponde a $SQ_{Reg} = 357.53$ e a segunda linha (`Residuals`) a $SQ_{Res} = 744.12$. Confirmamos que estes valores coincidem com os calculados manualmente. O $SQ_{Total}$ não aparece na tabela mais pode ser facilmente obtido pela soma dos outros dois.\n\nO coeficiente de determinação $R^2$ pode ser obtido pela função `summary`:\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nR2_rk_func <- summary(mod_rikz)$r.squared\ncat(\"R² (summary):\", round(R2_rk_func, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nR² (summary): 0.3245 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Relação com o coeficiente de correlação de Pearson\nr_rk <- cor(rikz$Richness, rikz$NAP)\ncat(\"r² (Pearson):\", round(r_rk^2, 4), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nr² (Pearson): 0.3245 \n```\n\n\n:::\n:::\n\n::: {.cell}\n\n:::\n\n\n\nOs três valores são idênticos, confirmando a relação $R^2 = r^2$ na regressão simples.\n\n### Interpretação\n\nO modelo de regressão linear $Richness \\sim NAP$ explica 32.5% da variação total na riqueza de espécies ($R^2 = 0.3245$). Em termos das somas dos quadrados:\n\n$$SQ_{Total} = SQ_{Reg} + SQ_{Res}$$ $$1101.6 = 357.5 + 744.1$$\n\nOs 67.6% restantes da variação não são explicados pelo NAP e estão atribuídos ao resíduo — podem refletir a influência de outras variáveis ambientais, variação natural entre espécies ou erros de medição.\n\n### Visualização da partição\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ndf_rikz_plot <- rikz |>\n  mutate(\n    Yfit = Yfit_rk,\n    Ybar = Ybar_rk\n  )\n\nggplot(df_rikz_plot, aes(x = NAP, y = Richness)) +\n  geom_hline(yintercept = Ybar_rk, linetype = \"dashed\",\n             color = \"gray40\", linewidth = 0.8) +\n\n  # Desvios da regressão (verde): Ybar -> Yfit\n  geom_segment(\n    aes(xend = NAP, y = Ybar, yend = Yfit, color = \"reg\"),\n    alpha = 0.5, linewidth = 0.8\n  ) +\n\n  # Resíduos (vermelho): Yfit -> Y\n  geom_segment(\n    aes(xend = NAP, y = Yfit, yend = Richness, color = \"res\"),\n    alpha = 0.5, linewidth = 0.8\n  ) +\n\n  geom_smooth(method = \"lm\", se = FALSE, color = \"steelblue\", linewidth = 1.2) +\n  geom_point(size = 2.5, alpha = 0.8) +\n\n  annotate(\"text\", x = min(rikz$NAP) + 0.2, y = Ybar_rk + 1.8,\n           label = expression(bar(Y)), size = 4.5, color = \"gray40\") +\n  annotate(\"text\", x = 2.2, y = 18,\n           label = as.expression(bquote(R^2 == .(R2_rk))),\n           size = 5, color = \"steelblue\") +\n\n  scale_color_manual(\n    name = \"Partição da Soma dos Quadrados\",\n    values = c(reg = \"forestgreen\", res = \"firebrick\"),\n    breaks = c(\"reg\", \"res\"),\n    labels = c(\n      reg = expression(hat(Y)[i] - bar(Y) ~ \"(desvio explicado)\"),\n      res = expression(Y[i] - hat(Y)[i] ~ \"(resíduo)\")\n    )\n  ) +\n\n  labs(x = \"NAP\", y = \"Richness (n° de espécies)\", color = NULL) +\n  theme_classic(base_size = 13) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Partição da soma dos quadrados no modelo Richness ~ NAP (RIKZ). A linha tracejada representa a média geral de Richness. Em verde, os desvios da regressão; em vermelho, os resíduos.](particao-soma-quadrados-r2_files/figure-html/fig-rikz-particao-1.png){#fig-rikz-particao fig-align='center' width=768}\n:::\n:::\n\n\n\nNa @fig-rikz-particao, os segmentos verdes representam os desvios de $\\hat{Y}_i$ em relação a $\\bar{Y}$ ($SQ_{Reg}$) e os segmentos vermelhos representam os resíduos $e_i = Y_i - \\hat{Y}_i$ ($SQ_{Res}$). A soma dos quadrados de todos os segmentos verdes mais a soma dos quadrados de todos os segmentos vermelhos é igual à soma dos quadrados de todos os desvios totais ($SQ_{Total}$).",
    "supporting": [
      "particao-soma-quadrados-r2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}