{
  "hash": "e8675b96ed4150452a3f38418ed12689",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Medidas de posição: transformação Z\"\ndescription: \"Transformação Z para padronizar distribuições, facilitando comparações entre diferentes escalas de medida.\"\ncategories: [\n          \"R\",\n          \"Análise de dados\",\n          \"Estatística descritiva\",\n          \"Padronização de dados\",\n          \"Índice Z\"\n        ]\n\nimage: \"images/escorez-logo.jpg\"\nexecute:\n  echo: true\n  warning: false\n  include: true\n  message: false\nformat:\n  html:\n    code-fold: false\n---\n\n\n\n\n:::{.callout-tip collapse=\"true\"}\n## Pacotes e funções utilizados\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(gt)\nlibrary(patchwork)\nsource('scripts/normal-empirica-gg.r')\n```\n:::\n\n\n\n\n:::\n\nO **índice (ou escore) $Z$** indica a posição de uma observação particular ($X_i$) dentro de uma distribuição, relacionando a posição de $X_i$ com a **média** e o **desvio padrão** da distribuição de $X$. Suponha uma variável com média $\\overline{X}$ e desvio padrão $s$. O índice de $Z_i$ para uma observação $i$ particular é calculado por:\n\n$$Z_i = \\frac{X_i - \\overline{X}}{s}$$\n\nSeja, por exemplo, a variável $X$:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1)\nX <- round(rnorm(20, 10, 2), 1)\nnX <- length(X)\nsX <- sort(X)\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n\n\n$X$ = 8.7, 10.4, 8.3, 13.2, 10.7, 8.4, 11, 11.5, 11.2, 9.4, 13, 10.8, 8.8, 5.6, 12.2, 9.9, 10, 11.9, 11.6, 11.2 \n\nCom média e desvio padrão $\\overline{X} = 10.39$ e $s = 1.82$, respectivamente.\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\nO índice $Z_i$ para a $3a$ observação $X_{3} = 8.3$ pode ser obtido por:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\ni <- 3\nXm <- mean(X)\nXsd <- sd(X)\nZi <- (X[i] - Xm) / Xsd\n```\n:::\n\n\n\n\n$Z_8.3 = \\frac{8.3 - 10.39}{1.82} = -1.15$\n\n## Interpretando o valor de $Z$\n\nO cálculo do índice $Z$ passa pela **centralização** e **padronização** da variável $X$:\n\n1. **Centralização**: a porção $X_i - \\overline{X}$ mede o *desvio* de cada observação, isto é, a distância (positiva ou negativa) entre $X_i$ e $\\overline{X}$. O termo centralização refere-se ao comportamento dos desvios estarem distribuídos ao redor de zero, isto é, a média dos desvios é zero.\n\n$$\\sum_{i=1}^{n}\\frac{(X_i - \\overline{X})}{n} = 0$$\n\n2. **Padronização**: ao dividirmos a quantia $X_i - \\overline{X}$ pelo desvio padrão de $X$, obtemos a nova variável denominada $Z$. O termo padronização refere-se ao fato de o desvio padrão de $Z$ ser igual a $1$.\n\nA **transformação $Z$** consiste, portanto, em gerar uma nova variável com média $\\overline{Z} = 0$ e desvio padrão $s_{Z} = 1$. \n\nDeste modo, o valor de $Z_i$ associado a uma observação $X_i$ particular nos indica **quantos desvios padrões** $X_i$ está acima ou abaixo da média de seu grupo. \n\n:::{.callout-note}\n## Relação $Z$ e $X$\n\n- Se $Z_i = 0$, então $X_i = \\overline{X}$;\n- Se $Z_i > 0$, então $X_i > \\overline{X}$;\n- Se $Z_i < 0$, então $X_i < \\overline{X}$;\n\n:::\n\nPara uma distribuição com média igual a $10$ e desvio padrão igual a $3$, por exemplo, uma observação $X_i = 16$ terá um valor de $Z = \\frac{16-10}{3} = 2$, indicando que está **dois desvios padrões** acima da média de $X$.\n\n## Cálculo de $Z$ no ambiente R\n\nSeja:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nset.seed(1)\nX <- round(rnorm(20, 10, 2), 1)\n```\n:::\n\n\n\n\n$X$ = 8.7, 10.4, 8.3, 13.2, 10.7, 8.4, 11, 11.5, 11.2, 9.4, 13, 10.8, 8.8, 5.6, 12.2, 9.9, 10, 11.9, 11.6, 11.2\n\n$Z$ pode ser obtido pelos comandos:\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nXm <- mean(X)\nXsd <- sd(X)\nZ <- (sort(X) - Xm) / Xsd\n```\n:::\n\n\n\n\nPodemos ver na @tbl-z-score os valores de cada observação $X_i$ e dos respectivos valores de $Z_i$ em ordem crescente.\n\n\n\n\n::: {#tbl-z-score .cell tbl-cap='Associação entre uma distribuição X e a transformação Z.'}\n\n```{.r .cell-code  code-fold=\"true\"}\nPosicao_k <- paste(1:length(X), \"a Posição\", sep = \"\")\ndf <- tibble(`Posicao k` = Posicao_k, `X ordenado` = sX, Z = round(Z, 2)) |>\n  add_row(\n    `Posicao k` = c(\"Média\", \"Desvio padrão\"),\n    `X ordenado` = c(round(mean(sX), 2), round(sd(sX), 2)),\n    Z = c(round(mean(Z), 2), round(sd(Z), 2))\n  )\n\ndf |>\n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jfottzlywf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jfottzlywf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jfottzlywf thead, #jfottzlywf tbody, #jfottzlywf tfoot, #jfottzlywf tr, #jfottzlywf td, #jfottzlywf th {\n  border-style: none;\n}\n\n#jfottzlywf p {\n  margin: 0;\n  padding: 0;\n}\n\n#jfottzlywf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jfottzlywf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jfottzlywf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jfottzlywf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jfottzlywf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jfottzlywf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jfottzlywf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jfottzlywf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jfottzlywf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jfottzlywf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jfottzlywf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jfottzlywf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jfottzlywf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jfottzlywf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jfottzlywf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jfottzlywf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jfottzlywf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jfottzlywf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jfottzlywf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jfottzlywf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jfottzlywf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jfottzlywf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jfottzlywf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jfottzlywf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jfottzlywf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jfottzlywf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jfottzlywf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jfottzlywf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jfottzlywf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jfottzlywf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jfottzlywf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jfottzlywf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jfottzlywf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jfottzlywf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jfottzlywf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jfottzlywf .gt_left {\n  text-align: left;\n}\n\n#jfottzlywf .gt_center {\n  text-align: center;\n}\n\n#jfottzlywf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jfottzlywf .gt_font_normal {\n  font-weight: normal;\n}\n\n#jfottzlywf .gt_font_bold {\n  font-weight: bold;\n}\n\n#jfottzlywf .gt_font_italic {\n  font-style: italic;\n}\n\n#jfottzlywf .gt_super {\n  font-size: 65%;\n}\n\n#jfottzlywf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jfottzlywf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jfottzlywf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jfottzlywf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jfottzlywf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jfottzlywf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jfottzlywf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jfottzlywf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jfottzlywf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Posicao-k\">Posicao k</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"X-ordenado\">X ordenado</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Z\">Z</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">1a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">5.60</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">-2.63</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">2a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">8.30</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">-1.15</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">3a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">8.40</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">-1.09</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">4a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">8.70</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">-0.93</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">5a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">8.80</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">-0.87</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">6a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">9.40</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">-0.54</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">7a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">9.90</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">-0.27</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">8a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">10.00</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">-0.21</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">9a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">10.40</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">0.01</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">10a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">10.70</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">0.17</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">11a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">10.80</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">0.23</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">12a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">11.00</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">0.34</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">13a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">11.20</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">0.45</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">14a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">11.20</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">0.45</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">15a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">11.50</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">0.61</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">16a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">11.60</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">0.66</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">17a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">11.90</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">0.83</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">18a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">12.20</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">0.99</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">19a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">13.00</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">1.43</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">20a Posição</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">13.20</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">1.54</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">Média</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">10.39</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">0.00</td></tr>\n    <tr><td headers=\"Posicao k\" class=\"gt_row gt_left\">Desvio padrão</td>\n<td headers=\"X ordenado\" class=\"gt_row gt_right\">1.82</td>\n<td headers=\"Z\" class=\"gt_row gt_right\">1.00</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nPodemos comparar graficamente as distribuições das variáveis $X$ e $Z$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nhX <- ggplot(df, aes(x = `X ordenado`)) +\n  geom_histogram(fill = 'darkblue', color = 'white', bins = 9) +\n  ylab('Frequência') +\n  scale_x_continuous(n.breaks = 7) +\n  theme_classic(base_size = 20)\n\nhZ <- ggplot(df, aes(x = Z)) +\n  geom_histogram(fill = 'darkblue', color = 'white', bins = 9) +\n  ylab('Frequência') +\n  scale_x_continuous(n.breaks = 7) +\n  theme_classic(base_size = 20)\n\nhX / hZ\n```\n\n::: {.cell-output-display}\n![Histogramas representando a distribuição de X e Z.](escorez_files/figure-html/fig-z-score-1.png){#fig-z-score width=768}\n:::\n:::\n\n\n\n\nVeja na @tbl-z-score que conforme o valor de $X_i$ se distancia da média de $X = 10.39$, mais distante de zero será o valor de $Z_i$. Neste exemplo, as observações mais extremas de $X$ estão, respectivamente, a -2.63 desvios padrões abaixo e 1.54 desvios padrões acima da média. Como discutido acima, a nova variável $Z$ tem média $\\overline{Z} = 0$ (está centralizada) e desvio padrão $s_Z = 1$ (está padronizada). \n\n## Obtendo a transformação $Z$ a partir de uma tabela de dados \n\nImporte a base de dados `Reservatorios_Parana_parcial.csv`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nres <- read_delim(\n  file = \"https://raw.githubusercontent.com/FCopf/datasets/refs/heads/main/Reservatorios_Parana_parcial.csv\",\n  delim = \",\",\n  locale = locale(decimal_mark = \".\", encoding = \"latin1\")\n)\n```\n:::\n\n\n\n\nUtilizando a função `mutate`, vamos manter somente a variável `CPUE` e criar outra coluna denominada `CPUE_z`.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_z <- res |> \n  select(CPUE) |> \n  mutate(CPUE_z = (CPUE - mean(CPUE)) / sd(CPUE)) |> \n  round(2)\n\ndf_z |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"yhlywxfzgs\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yhlywxfzgs table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yhlywxfzgs thead, #yhlywxfzgs tbody, #yhlywxfzgs tfoot, #yhlywxfzgs tr, #yhlywxfzgs td, #yhlywxfzgs th {\n  border-style: none;\n}\n\n#yhlywxfzgs p {\n  margin: 0;\n  padding: 0;\n}\n\n#yhlywxfzgs .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yhlywxfzgs .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yhlywxfzgs .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yhlywxfzgs .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yhlywxfzgs .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yhlywxfzgs .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yhlywxfzgs .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yhlywxfzgs .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yhlywxfzgs .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yhlywxfzgs .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yhlywxfzgs .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yhlywxfzgs .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yhlywxfzgs .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yhlywxfzgs .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yhlywxfzgs .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yhlywxfzgs .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yhlywxfzgs .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yhlywxfzgs .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yhlywxfzgs .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yhlywxfzgs .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yhlywxfzgs .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yhlywxfzgs .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yhlywxfzgs .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yhlywxfzgs .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yhlywxfzgs .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yhlywxfzgs .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yhlywxfzgs .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yhlywxfzgs .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yhlywxfzgs .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yhlywxfzgs .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yhlywxfzgs .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yhlywxfzgs .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yhlywxfzgs .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yhlywxfzgs .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yhlywxfzgs .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yhlywxfzgs .gt_left {\n  text-align: left;\n}\n\n#yhlywxfzgs .gt_center {\n  text-align: center;\n}\n\n#yhlywxfzgs .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yhlywxfzgs .gt_font_normal {\n  font-weight: normal;\n}\n\n#yhlywxfzgs .gt_font_bold {\n  font-weight: bold;\n}\n\n#yhlywxfzgs .gt_font_italic {\n  font-style: italic;\n}\n\n#yhlywxfzgs .gt_super {\n  font-size: 65%;\n}\n\n#yhlywxfzgs .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yhlywxfzgs .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yhlywxfzgs .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yhlywxfzgs .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yhlywxfzgs .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yhlywxfzgs .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yhlywxfzgs .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#yhlywxfzgs .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#yhlywxfzgs div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CPUE\">CPUE</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CPUE_z\">CPUE_z</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">9.22</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.47</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">28.73</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">2.17</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">11.59</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.15</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">30.76</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">2.45</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">5.95</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.92</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">7.75</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.67</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">7.51</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.70</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">4.01</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-1.18</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">20.83</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">1.10</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">2.43</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-1.39</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">12.55</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.02</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">11.73</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.13</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">13.72</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">0.14</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">16.50</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">0.52</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">4.71</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-1.08</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">7.95</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.64</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">13.12</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">0.06</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">16.10</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">0.46</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">11.74</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.13</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">17.95</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">0.71</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">13.86</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">0.16</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">13.04</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">0.05</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">7.35</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.73</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">20.92</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">1.12</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">13.67</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">0.13</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">21.82</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">1.24</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">6.29</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.87</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">9.40</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.45</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">5.60</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-0.96</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">2.05</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">-1.45</td></tr>\n    <tr><td headers=\"CPUE\" class=\"gt_row gt_right\">24.88</td>\n<td headers=\"CPUE_z\" class=\"gt_row gt_right\">1.65</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\nSe calcularmos a média e o desvio padrão das variáveis, veremos que `CPUE` mantém os valores originais, enquanto `CPUE_z` terá média igual a $0$ e desvio padrão igual a $1$.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf_z |> \n  summarize(CPUE_media = mean(CPUE),\n            CPUE_dp = sd(CPUE),\n            CPUE_z_media = round(mean(CPUE_z), 2),\n            CPUE_z_dp = round(sd(CPUE_z), 2)) |> \n  gt()\n```\n\n::: {.cell-output-display}\n\n```{=html}\n<div id=\"jfxnbmrvnf\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#jfxnbmrvnf table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#jfxnbmrvnf thead, #jfxnbmrvnf tbody, #jfxnbmrvnf tfoot, #jfxnbmrvnf tr, #jfxnbmrvnf td, #jfxnbmrvnf th {\n  border-style: none;\n}\n\n#jfxnbmrvnf p {\n  margin: 0;\n  padding: 0;\n}\n\n#jfxnbmrvnf .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#jfxnbmrvnf .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#jfxnbmrvnf .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#jfxnbmrvnf .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#jfxnbmrvnf .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jfxnbmrvnf .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jfxnbmrvnf .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#jfxnbmrvnf .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#jfxnbmrvnf .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#jfxnbmrvnf .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#jfxnbmrvnf .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#jfxnbmrvnf .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#jfxnbmrvnf .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#jfxnbmrvnf .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#jfxnbmrvnf .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#jfxnbmrvnf .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#jfxnbmrvnf .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#jfxnbmrvnf .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#jfxnbmrvnf .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jfxnbmrvnf .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#jfxnbmrvnf .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#jfxnbmrvnf .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#jfxnbmrvnf .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jfxnbmrvnf .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#jfxnbmrvnf .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#jfxnbmrvnf .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jfxnbmrvnf .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jfxnbmrvnf .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#jfxnbmrvnf .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jfxnbmrvnf .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#jfxnbmrvnf .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#jfxnbmrvnf .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jfxnbmrvnf .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jfxnbmrvnf .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#jfxnbmrvnf .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#jfxnbmrvnf .gt_left {\n  text-align: left;\n}\n\n#jfxnbmrvnf .gt_center {\n  text-align: center;\n}\n\n#jfxnbmrvnf .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#jfxnbmrvnf .gt_font_normal {\n  font-weight: normal;\n}\n\n#jfxnbmrvnf .gt_font_bold {\n  font-weight: bold;\n}\n\n#jfxnbmrvnf .gt_font_italic {\n  font-style: italic;\n}\n\n#jfxnbmrvnf .gt_super {\n  font-size: 65%;\n}\n\n#jfxnbmrvnf .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#jfxnbmrvnf .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#jfxnbmrvnf .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#jfxnbmrvnf .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#jfxnbmrvnf .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#jfxnbmrvnf .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#jfxnbmrvnf .gt_indent_5 {\n  text-indent: 25px;\n}\n\n#jfxnbmrvnf .katex-display {\n  display: inline-flex !important;\n  margin-bottom: 0.75em !important;\n}\n\n#jfxnbmrvnf div.Reactable > div.rt-table > div.rt-thead > div.rt-tr.rt-tr-group-header > div.rt-th-group:after {\n  height: 0px !important;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CPUE_media\">CPUE_media</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CPUE_dp\">CPUE_dp</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CPUE_z_media\">CPUE_z_media</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"CPUE_z_dp\">CPUE_z_dp</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"CPUE_media\" class=\"gt_row gt_right\">12.70097</td>\n<td headers=\"CPUE_dp\" class=\"gt_row gt_right\">7.3701</td>\n<td headers=\"CPUE_z_media\" class=\"gt_row gt_right\">0</td>\n<td headers=\"CPUE_z_dp\" class=\"gt_row gt_right\">1</td></tr>\n  </tbody>\n  \n</table>\n</div>\n```\n\n:::\n:::\n\n\n\n\n## Valores esperados de $Z$ em uma distribuição normal padronizada\n\nA interpretação de $Z$ faz sentido quando desejamos posicionar uma determinada observação $X_i$ como função da média e desvio padrão de seu grupo. Adicionalmente, se uma variável $X$ puder ser descrita adequadamente por uma **distribuição normal de probabilidades**, existe uma regra empírica que permite determinar os percentuais das observações acima e abaixo de limites conhecidos.\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\n# Ver função completa no arquivo 'scripts/normal-empirica-gg.r'\nnormal_empirica_gg()\n```\n\n::: {.cell-output-display}\n![Áreas de probabilidade em uma distribuição normal.](escorez_files/figure-html/fig-normal-empirica-gg-1.png){#fig-normal-empirica-gg width=672}\n:::\n:::\n\n\n\n\nNa @fig-normal-empirica-gg, vemos que existe uma probabilidade de aproximadamente $68\\%$ de que uma observação tomada ao acaso esteja entre os limites de $-1$ e $1$ desvios padrões da média. Existe ainda uma probabilidade de aproximadamente $95\\%$ de que uma observação esteja entre $-2$ e $2$ desvios padrões da média. Por outro lado, é muito improvável encontrarmos ao acaso uma observação a mais de $3$ desvios padrões distantes da média. Isto deverá ocorrer em somente cerca de $0,26\\%$ dos casos em que sortearmos uma amostra aleatoriamente.\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n:::{.callout-note}\n## Uso da distribuição normal empírica\n\nSuponha que a distribuição de altura de homens adultos siga uma distribuição normal com média $\\mu = 175$ cm e desvio padrão $\\sigma = 10$ cm. \n\n\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nmH <- 175\nsdH <- 10\nlim <- 2\nlinf <- round(mH - lim * sdH, 2)\nlsup <- round(mH + lim * sdH, 2)\n```\n:::\n\n\n\n\nNeste caso, se tomarmos os limites entre $-2$ e $+2$ desvios padrões teremos: \n\n$\\mu - 2 \\times \\sigma = 175 - 2 \\times 10 = 155$ cm\n\ne\n\n$\\mu + 2 \\times \\sigma = 175 + 2 \\times 10 = 195$ cm\n\nEstes resultados sugerem que nesta população temos somente cerca de $5\\%$ dos homens adultos com mais de $195$ cm ou menos de $155$ cm de altura.\n\n:::",
    "supporting": [
      "escorez_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}